-- Add missing columns
ALTER TABLE capabilities ADD COLUMN IF NOT EXISTS provider_wallet text;
ALTER TABLE capabilities ADD COLUMN IF NOT EXISTS usage_count integer DEFAULT 0;
ALTER TABLE capabilities ADD COLUMN IF NOT EXISTS rating numeric(3,1) DEFAULT 4.5;
ALTER TABLE capabilities ADD COLUMN IF NOT EXISTS provider_name text;

-- Delete existing and re-seed all 114
DELETE FROM capabilities;

INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('AI Agent Builder', 'agent-builder', 'Describe what you want. Get a complete, ready-to-run AI agent with personality, tools, cron jobs, and Agent Bazaar skill integrations.', 'The meta skill that creates agents. Describe your desired functionality in natural language and get a complete OpenClaw agent with SOUL.md, AGENTS.md, TOOLS.md, cron jobs, and Agent Bazaar skill integrations. Every agent created becomes a customer of Agent Bazaar skills — the ultimate flywheel.', 'api', 'automation', 0.01, '🤖', ARRAY['agent','builder','openclaw','automation','no-code'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 99999999, 5, 'AgentForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('GPT-4 Code Review', 'gpt4-code-review', 'Automated code review via GPT-4. Submit a diff, get security analysis, bug detection, and style suggestions.', 'Production-grade code review powered by GPT-4. Catches security vulnerabilities, logic bugs, and style violations in any language.', 'api', 'code-generation', 0.01, '🔍', ARRAY['code-review','security','gpt-4','developer'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 284000, 4.9, 'DevForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('DALL-E Image Generator', 'dalle-image-gen', 'Generate images from text prompts. x402-enabled — agents can generate images autonomously.', 'High-quality image generation via DALL-E 3. Supports all aspect ratios, styles, and quality levels.', 'api', 'image-generation', 0.01, '🎨', ARRAY['image','dalle','generation','creative'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 512000, 4.7, 'PixelMint');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Web Scraper API', 'web-scraper-api', 'Extract structured data from any URL. Handles JS-rendered pages, anti-bot, and pagination.', 'Enterprise-grade web scraping. Returns clean JSON from any webpage with automatic anti-detection.', 'api', 'web-scraping', 0.01, '🕸️', ARRAY['scraping','web','data','extraction'], true, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1340000, 4.6, 'CrawlLab');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('SEO Analyzer', 'seo-analyzer', 'Full SEO audit for any URL. Technical SEO, content scoring, keyword gaps, and competitor analysis.', 'Comprehensive SEO analysis returning actionable recommendations. Covers on-page, technical, and content optimization.', 'api', 'content-writing', 0.01, '📈', ARRAY['seo','marketing','analysis','content'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 89000, 4.8, 'RankForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('SQL Query Generator', 'sql-query-gen', 'Natural language to SQL. Supports PostgreSQL, MySQL, SQLite, and BigQuery dialects.', 'Describe what you need in English, get production-ready SQL. Handles complex joins, CTEs, and window functions.', 'api', 'code-generation', 0.01, '🗄️', ARRAY['sql','database','query','natural-language'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 167000, 4.5, 'QueryCraft');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('git-audit CLI', 'git-audit-cli', 'CLI tool that audits your git history for secrets, large files, and compliance issues.', 'Install via npm/brew. Scans entire git history for leaked credentials, oversized binaries, and policy violations.', 'cli', 'code-generation', 0.01, '🔐', ARRAY['git','security','cli','audit'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 45000, 4.8, 'SecureDev');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('CSV Intelligence', 'csv-intelligence', 'Upload a CSV, ask questions in natural language. Returns charts, stats, and insights.', 'Data analysis without code. Upload any CSV and get instant statistical analysis, visualizations, and AI-powered insights.', 'api', 'data-analysis', 0.01, '📊', ARRAY['csv','analytics','data','visualization'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 73000, 4.4, 'DataPilot');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Blog Post Writer', 'blog-post-writer', 'Generate SEO-optimized long-form blog posts. Includes outline, meta tags, and internal linking suggestions.', 'Feed it a keyword and tone, get a publish-ready blog post with SEO optimization baked in.', 'api', 'content-writing', 0.01, '✍️', ARRAY['blog','seo','writing','content'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 198000, 4.7, 'ContentForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Crypto Price Oracle', 'crypto-price-oracle', 'Real-time and historical crypto prices with technical indicators. Agent-native trading data.', 'Access real-time prices, OHLCV data, and 50+ technical indicators for any crypto pair. Built for trading agents.', 'api', 'trading', 0.01, '₿', ARRAY['crypto','trading','prices','oracle'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2100000, 4.6, 'ChainData');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Research Summarizer', 'research-summarizer', 'Summarize academic papers, reports, and documents. Returns structured key findings and citations.', 'Paste a URL or upload a PDF — get a structured summary with key findings, methodology, and citation-ready references.', 'api', 'research', 0.01, '🔬', ARRAY['research','academic','summary','papers'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 56000, 4.5, 'ScholarAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('deploy-cli', 'deploy-cli', 'One-command deploy to any cloud. Supports Vercel, AWS, GCP, and Fly.io with zero config.', 'CLI tool that detects your framework and deploys to your preferred cloud provider with sensible defaults.', 'cli', 'automation', 0.01, '🚀', ARRAY['deploy','cli','cloud','devops'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 34000, 4.3, 'ShipFast');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Email Composer Skill', 'email-composer-skill', 'Agent skill for composing context-aware emails. Drop into any agent framework as a tool.', 'A composable skill that any AI agent can use. Given context and intent, drafts professional emails with proper tone.', 'skill', 'automation', 0.01, '📧', ARRAY['email','skill','agent','automation'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 127000, 4.6, 'ToolSmith');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Memory Store Skill', 'memory-store-skill', 'Persistent vector memory for any agent. Store, retrieve, and search context across sessions.', 'Give any agent long-term memory. ChromaDB-backed vector store with semantic search — drop in as a skill via x402.', 'skill', 'automation', 0.01, '🧠', ARRAY['memory','vector','rag','agent','skill'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 340000, 4.9, 'MemoryAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Web Search Skill', 'web-search-skill', 'Real-time web search for agents. Returns structured results with snippets and sources.', 'Drop-in web search capability for any agent framework. Returns ranked results with full page content extraction.', 'skill', 'research', 0.01, '🔎', ARRAY['search','web','skill','agent','research'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 890000, 4.8, 'SearchCraft');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('bankr-cli', 'bankr-cli', 'CLI for on-chain agent actions. Send tokens, check balances, swap — all from a shell or agent.', 'The self-funding agent CLI. Built for agents that need to interact with Base and EVM chains autonomously. x402-compatible.', 'cli', 'trading', 0.01, '🏦', ARRAY['crypto','cli','onchain','agent','base'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 210000, 4.9, 'Bankr');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Scheduler Skill', 'scheduler-skill', 'Give any agent the ability to schedule future tasks, reminders, and recurring jobs.', 'Cron-based task scheduling as a composable skill. Agents can schedule their own follow-ups and recurring workflows.', 'skill', 'automation', 0.01, '⏰', ARRAY['scheduling','cron','skill','agent','automation'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 67000, 4.5, 'TimeCraft');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Ethereum DeFi Oracle', 'ethereum-defi-oracle', 'Real-time DeFi metrics for Ethereum. TVL, APY, liquidity pools, and yield farming data across all major protocols.', 'Comprehensive DeFi data feed for Ethereum. Access real-time TVL, yields, and liquidity metrics from Uniswap, Curve, Aave, Compound, and 100+ protocols.', 'api', 'trading', 0.01, '⚡', ARRAY['ethereum','defi','oracle','yield','tvl'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 456000, 4.8, 'DeFiData');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('MEV Bot Framework', 'mev-bot-framework', 'Detect and execute MEV opportunities. Arbitrage, liquidation, and sandwich detection across DEXs.', 'Production-ready MEV bot framework. Scans mempool for arbitrage and liquidation opportunities with gas optimization and flashloan integration.', 'api', 'trading', 0.01, '🤖', ARRAY['mev','arbitrage','bot','flashloan','defi'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 123000, 4.6, 'MEVLabs');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Solana Trading Engine', 'solana-trading-engine', 'High-speed Solana trading with Jupiter aggregation. Instant swaps, position sizing, and slippage protection.', 'Lightning-fast Solana trades via Jupiter DEX aggregator. Built for high-frequency trading agents with sub-second execution.', 'api', 'trading', 0.01, '☀️', ARRAY['solana','jupiter','dex','trading','swap'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 789000, 4.7, 'SolTrade');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Options Strategy Builder', 'options-strategy-builder', 'Automated options strategies for stocks and crypto. Greeks calculation, risk management, and execution signals.', 'Build and backtest options strategies automatically. Calculates Greeks, manages risk, and provides execution signals for covered calls, straddles, and complex spreads.', 'api', 'trading', 0.01, '📊', ARRAY['options','strategy','greeks','risk','trading'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 67000, 4.5, 'OptionsAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Vulnerability Scanner', 'vulnerability-scanner', 'Automated security scanning for web apps, APIs, and infrastructure. OWASP Top 10, CSRF, and injection attacks.', 'Enterprise-grade vulnerability scanning. Detects SQL injection, XSS, CSRF, and infrastructure misconfigurations. OWASP-compliant reports.', 'api', 'security', 0.01, '🛡️', ARRAY['security','vulnerability','owasp','penetration','audit'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 145000, 4.9, 'SecureScan');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Smart Contract Auditor', 'smart-contract-auditor', 'Automated smart contract security analysis. Detects reentrancy, overflow, and logic bugs in Solidity.', 'Professional smart contract auditing powered by Mythril and Slither. Identifies critical vulnerabilities before deployment.', 'api', 'security', 0.01, '🔐', ARRAY['solidity','audit','smart-contract','mythril','security'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 89000, 4.8, 'ChainAudit');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('DNS Security Monitor', 'dns-security-monitor', 'Monitor domains for DNS hijacking, subdomain takeovers, and certificate transparency logs.', 'Continuous DNS monitoring and threat detection. Alerts on suspicious changes, subdomain takeovers, and certificate anomalies.', 'api', 'security', 0.01, '🌐', ARRAY['dns','monitoring','certificates','subdomain','security'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 234000, 4.6, 'DNSGuard');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('API Penetration Tester', 'api-pen-tester', 'Automated API security testing. Authentication bypass, rate limiting, and injection vulnerability detection.', 'Comprehensive API penetration testing. Tests for auth bypass, rate limiting, SQL injection, and OWASP API Top 10 vulnerabilities.', 'api', 'security', 0.01, '🔧', ARRAY['api','penetration','testing','auth','injection'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 156000, 4.7, 'APISec');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('E2E Test Generator', 'e2e-test-generator', 'Generate Playwright and Cypress tests from user flows. Record interactions, generate test code automatically.', 'Turn user workflows into automated tests. Records browser interactions and generates production-ready Playwright or Cypress test suites.', 'api', 'testing', 0.01, '🎭', ARRAY['playwright','cypress','e2e','testing','automation'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 178000, 4.6, 'TestCraft');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Load Testing Engine', 'load-testing-engine', 'Distributed load testing for APIs and web apps. Realistic traffic patterns, global edge locations.', 'Simulate thousands of concurrent users from global edge locations. Realistic load patterns with detailed performance metrics and bottleneck detection.', 'api', 'testing', 0.01, '⚡', ARRAY['load-testing','performance','stress','scalability','k6'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 92000, 4.8, 'LoadLabs');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('API Test Suite Builder', 'api-test-builder', 'Generate comprehensive API test suites from OpenAPI specs. Contract testing, edge cases, and validation.', 'Automatically generate test cases from OpenAPI specifications. Includes contract testing, boundary value testing, and schema validation.', 'api', 'testing', 0.01, '🔌', ARRAY['api','openapi','contract-testing','validation','rest'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 134000, 4.5, 'APITest');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Mutation Testing Engine', 'mutation-testing-engine', 'Evaluate test suite quality with mutation testing. Detects weak tests and improves code coverage.', 'Advanced mutation testing for JavaScript, Python, and Java. Identifies gaps in test coverage by introducing code mutations and measuring test effectiveness.', 'api', 'testing', 0.01, '🧬', ARRAY['mutation-testing','coverage','quality','testing','javascript'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 67000, 4.4, 'MutantLabs');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('GitHub Actions Optimizer', 'github-actions-optimizer', 'Optimize GitHub Actions workflows. Reduce build times, costs, and detect configuration issues.', 'Analyze GitHub Actions workflows for performance bottlenecks, cost optimization opportunities, and security misconfigurations.', 'api', 'cicd', 0.01, '⚙️', ARRAY['github-actions','optimization','cicd','performance','cost'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 203000, 4.7, 'CIOptimizer');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Docker Security Scanner', 'docker-security-scanner', 'Scan container images for vulnerabilities, secrets, and misconfigurations. SBOM generation included.', 'Comprehensive container security scanning. Detects CVEs, leaked secrets, and Docker misconfigurations. Generates SBOMs for compliance.', 'api', 'cicd', 0.01, '🐳', ARRAY['docker','security','vulnerability','sbom','container'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 187000, 4.8, 'ContainerGuard');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Pipeline Generator', 'pipeline-generator', 'Generate CI/CD pipelines for any tech stack. Supports GitHub Actions, GitLab CI, Jenkins, and Azure DevOps.', 'Analyze your codebase and generate optimized CI/CD pipelines with testing, security scanning, and deployment stages for any platform.', 'api', 'cicd', 0.01, '🔄', ARRAY['pipeline','cicd','generator','github','gitlab'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 156000, 4.6, 'PipelineCraft');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Deployment Rollback Engine', 'deployment-rollback-engine', 'Intelligent deployment monitoring with automatic rollbacks. Health checks, canary deployments, blue-green.', 'Monitor deployments in real-time with automatic rollback on failure. Supports canary, blue-green, and rolling deployment strategies.', 'api', 'cicd', 0.01, '🔄', ARRAY['deployment','rollback','canary','blue-green','monitoring'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 89000, 4.9, 'DeployGuard');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Universal Translator API', 'universal-translator', 'High-quality translation for 100+ languages. Context-aware, domain-specific, with sentiment preservation.', 'Professional-grade translation powered by multiple AI models. Maintains context, tone, and cultural nuances across technical, creative, and business content.', 'api', 'translation', 0.01, '🌐', ARRAY['translation','multilingual','context','sentiment','localization'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2340000, 4.8, 'LinguaAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Code Translation Engine', 'code-translator', 'Convert code between programming languages. Supports 20+ languages with syntax and idiom preservation.', 'Translate code between Python, JavaScript, Go, Rust, Java, and 15+ other languages while preserving logic, patterns, and best practices.', 'api', 'translation', 0.01, '💻', ARRAY['code','programming','conversion','syntax','migration'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 167000, 4.5, 'CodeBridge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Document Localizer', 'document-localizer', 'Localize documents while preserving formatting. PDFs, Word docs, presentations with cultural adaptation.', 'Full document localization service. Translates and culturally adapts PDFs, Word documents, and presentations while maintaining original formatting.', 'api', 'translation', 0.01, '📄', ARRAY['localization','documents','pdf','formatting','cultural'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 98000, 4.7, 'DocTranslate');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Subtitle Generator', 'subtitle-generator', 'Generate accurate subtitles in 50+ languages. Auto-sync, speaker identification, and format conversion.', 'AI-powered subtitle generation with automatic timing, speaker identification, and translation. Outputs SRT, VTT, and other standard formats.', 'api', 'translation', 0.01, '📺', ARRAY['subtitles','video','transcription','translation','sync'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 234000, 4.6, 'SubCraft');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Voice Synthesis Engine', 'voice-synthesis-engine', 'Generate natural speech in 200+ voices and 40+ languages. Emotion control, SSML support, real-time streaming.', 'Advanced text-to-speech with emotional control, pronunciation tuning, and real-time streaming. Perfect for agents that need to speak.', 'api', 'voice-audio', 0.01, '🗣️', ARRAY['tts','voice','speech','emotion','multilingual'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1230000, 4.9, 'VoiceForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Audio Transcription Pro', 'audio-transcription-pro', 'High-accuracy transcription with speaker diarization, timestamps, and custom vocabulary support.', 'Professional-grade speech-to-text with speaker identification, precise timestamps, and domain-specific vocabulary. Handles noisy audio and multiple speakers.', 'api', 'voice-audio', 0.01, '🎙️', ARRAY['transcription','stt','diarization','timestamps','accuracy'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 567000, 4.8, 'TranscribeAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Music Generator API', 'music-generator-api', 'Generate original music from text prompts. Multiple genres, instruments, and mood controls.', 'Create original music tracks from descriptive prompts. Control genre, tempo, instruments, and mood to generate perfect background music for any content.', 'api', 'voice-audio', 0.01, '🎵', ARRAY['music','generation','ai','creative','audio'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 123000, 4.6, 'MelodyAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Sound Effects Library', 'sound-effects-library', 'Generate custom sound effects on-demand. Foley, ambient sounds, UI sounds, and audio branding.', 'AI-generated sound effects library with over 10,000 categories. Generate custom sounds from text descriptions or browse the curated collection.', 'api', 'voice-audio', 0.01, '🔊', ARRAY['sound-effects','foley','audio','ui','ambient'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 345000, 4.4, 'SoundForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Stripe Payment Processor', 'stripe-payment-processor', 'Process payments via Stripe with intelligent retry logic, fraud detection, and subscription management.', 'Full-featured Stripe integration for agents. Handles one-time payments, subscriptions, refunds, and disputes with intelligent retry mechanisms.', 'api', 'payments', 0.01, '💳', ARRAY['stripe','payments','subscriptions','fraud','retry'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 890000, 4.9, 'PaymentPro');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Crypto Payment Gateway', 'crypto-payment-gateway', 'Accept crypto payments in 50+ currencies. Auto-conversion, compliance reporting, and cold storage integration.', 'Multi-chain crypto payment processing. Accepts Bitcoin, Ethereum, stablecoins, and alt-coins with automatic conversion and compliance reporting.', 'api', 'payments', 0.01, '₿', ARRAY['crypto','bitcoin','ethereum','payments','stablecoin'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 234000, 4.7, 'CryptoPay');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Invoice Generator Pro', 'invoice-generator-pro', 'Generate professional invoices with payment links, automated reminders, and multi-currency support.', 'Complete invoicing solution with customizable templates, automatic payment reminders, tax calculations, and integration with major payment processors.', 'api', 'payments', 0.01, '📧', ARRAY['invoicing','billing','reminders','payments','taxes'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 156000, 4.6, 'InvoiceAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Expense Tracker API', 'expense-tracker-api', 'Automatic expense categorization and receipt processing. OCR, tax deduction detection, reporting.', 'AI-powered expense management. Processes receipts via OCR, categorizes expenses automatically, and generates tax-ready reports.', 'api', 'payments', 0.01, '📊', ARRAY['expenses','ocr','receipts','taxes','categorization'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 187000, 4.8, 'ExpenseBot');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Multi-Channel Notifier', 'multi-channel-notifier', 'Send notifications across Slack, Discord, SMS, email, push notifications, and webhooks from one API.', 'Unified notification API supporting 15+ channels. Smart delivery routing, retry logic, and delivery tracking across all platforms.', 'api', 'notifications', 0.01, '📱', ARRAY['notifications','slack','discord','sms','email'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 3450000, 4.8, 'NotifyHub');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Smart Alert Manager', 'smart-alert-manager', 'Intelligent alert routing with escalation, deduplication, and on-call scheduling. PagerDuty integration.', 'Advanced alert management with smart routing, noise reduction, escalation policies, and seamless integration with existing on-call tools.', 'api', 'notifications', 0.01, '🚨', ARRAY['alerts','escalation','on-call','pagerduty','deduplication'], true, 'spotlight', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 234000, 4.9, 'AlertForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Calendar Sync Engine', 'calendar-sync-engine', 'Sync events across Google, Outlook, Apple Calendar, and Calendly. Smart conflict detection and resolution.', 'Universal calendar synchronization with intelligent conflict resolution, timezone handling, and meeting scheduling across all major platforms.', 'api', 'scheduling', 0.01, '📅', ARRAY['calendar','sync','google','outlook','scheduling'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 456000, 4.7, 'CalendarHub');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Meeting Scheduler AI', 'meeting-scheduler-ai', 'Intelligent meeting scheduling with availability optimization, timezone handling, and automated confirmations.', 'AI-powered meeting coordination. Finds optimal times across participants, handles timezone complexities, and manages the entire scheduling workflow.', 'api', 'scheduling', 0.01, '🤝', ARRAY['meetings','scheduling','ai','optimization','automation'], true, 'featured', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 178000, 4.8, 'MeetingAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Task Automation Engine', 'task-automation-engine', 'Advanced task orchestration with dependencies, retries, and parallel execution. Zapier for agents.', 'Build complex automation workflows with conditional logic, error handling, and parallel processing. Connect any API or service.', 'api', 'scheduling', 0.01, '⚙️', ARRAY['automation','workflows','orchestration','dependencies','parallel'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 267000, 4.6, 'TaskForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Resource Monitor Pro', 'resource-monitor-pro', 'Monitor server resources, API quotas, and service health with predictive alerting and auto-scaling triggers.', 'Comprehensive resource monitoring with ML-powered predictions. Monitors servers, databases, APIs, and triggers auto-scaling before issues occur.', 'api', 'scheduling', 0.01, '📊', ARRAY['monitoring','resources','predictive','auto-scaling','health'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 189000, 4.7, 'MonitorLabs');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Email Sender API', 'email-sender-api', 'Send transactional emails with delivery tracking, templates, and SMTP reliability.', 'Enterprise-grade email delivery service with automatic retries, bounce handling, and delivery analytics. Supports HTML templates, attachments, and custom headers.', 'api', 'automation', 0.01, '📧', ARRAY['email','transactional','smtp','templates'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2340, 4.7, 'EmailForge');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('PDF Parser', 'pdf-parser', 'Extract text, tables, and metadata from PDF documents with OCR support.', 'Advanced PDF processing with OCR for scanned documents, table extraction, form data parsing, and metadata extraction. Supports password-protected files.', 'api', 'data-analysis', 0.01, '📄', ARRAY['pdf','ocr','extraction','tables','documents'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1890, 4.6, 'DocProcess');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Translation API', 'translation-api', 'Translate text between 40+ languages with context awareness and quality optimization.', 'High-quality translation service supporting 40+ languages with context-aware processing, domain-specific terminology, and quality scoring.', 'api', 'content-writing', 0.01, '🌍', ARRAY['translation','multilingual','localization','i18n'], true, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 4230, 4.8, 'LinguaTech');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Voice Transcription', 'voice-transcription', 'Audio to text transcription via Whisper with speaker identification and timestamps.', 'Powered by OpenAI Whisper, supports multiple languages, speaker diarization, and precise timestamps. Handles noisy audio and multiple speakers.', 'api', 'automation', 0.01, '🎤', ARRAY['whisper','transcription','audio','speech-to-text'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1560, 4.5, 'AudioScribe');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Domain Checker', 'domain-checker', 'WHOIS lookups, DNS records, and domain availability checking in one API call.', 'Comprehensive domain intelligence including WHOIS data, DNS records, SSL certificate info, and availability status. Supports bulk queries.', 'api', 'web-scraping', 0.01, '🌐', ARRAY['whois','dns','domains','availability'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 3120, 4.4, 'DomainTools');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('SEO Analyzer', 'seo-analyzer-v2', 'On-page SEO audit for any URL with actionable recommendations and performance scoring.', 'Complete SEO analysis including meta tags, content structure, performance metrics, and competitor comparison. Generates actionable improvement suggestions.', 'api', 'data-analysis', 0.01, '📈', ARRAY['seo','audit','optimization','analytics'], true, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2780, 4.9, 'SEOPro');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('QR Code Generator', 'qr-code-generator', 'Generate QR codes from text, URLs, or data with customizable styling and formats.', 'Advanced QR code generation with custom colors, logos, error correction levels, and multiple output formats (PNG, SVG, PDF).', 'api', 'automation', 0.01, '📱', ARRAY['qr-code','generator','barcode','mobile'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 5670, 4.3, 'QRMaster');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Cron Job Manager', 'cron-job-manager', 'Schedule and monitor recurring tasks with failure notifications and retry logic.', 'Robust cron job scheduling with monitoring, alerting, retry policies, and detailed logs. Perfect for automating recurring workflows.', 'cli', 'automation', 0.01, '⏰', ARRAY['cron','scheduling','automation','monitoring'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1430, 4.6, 'CronLabs');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Database Migration Tool', 'database-migration-tool', 'Auto-generate SQL migrations with rollback support for multiple database engines.', 'Intelligent migration generation for PostgreSQL, MySQL, and SQLite with automatic rollback scripts, schema diffing, and data migration support.', 'cli', 'automation', 0.01, '🗄️', ARRAY['database','migration','sql','schema'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 890, 4.7, 'MigrationPro');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('API Load Tester', 'api-load-tester', 'Stress test any API endpoint with realistic traffic patterns and detailed metrics.', 'Comprehensive API load testing with configurable traffic patterns, response time analysis, throughput measurement, and bottleneck identification.', 'cli', 'automation', 0.01, '⚡', ARRAY['load-testing','performance','api','stress'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1240, 4.5, 'LoadTest');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Social Scheduler', 'social-scheduler', 'Queue and publish posts across multiple social media platforms with optimal timing.', 'Multi-platform social media scheduler supporting Twitter, LinkedIn, Facebook, and Instagram with best time analytics and engagement tracking.', 'skill', 'automation', 0.01, '📱', ARRAY['social-media','scheduling','automation','engagement'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2150, 4.4, 'SocialBot');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Lead Enrichment', 'lead-enrichment', 'Enrich contact data from email addresses with social profiles and company information.', 'Comprehensive lead enrichment service that finds social profiles, job titles, company data, and contact information from email addresses.', 'api', 'data-analysis', 0.01, '👤', ARRAY['leads','enrichment','contacts','crm'], true, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1680, 4.6, 'LeadGen');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Invoice Generator', 'invoice-generator', 'Create professional PDF invoices with payment links and automated follow-ups.', 'Complete invoicing solution with customizable templates, tax calculations, payment integration, and automated reminder systems.', 'api', 'automation', 0.01, '📋', ARRAY['invoicing','billing','pdf','payments'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 3450, 4.8, 'InvoicePro');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Plagiarism Checker', 'plagiarism-checker', 'Check text originality against billions of web pages and academic databases.', 'Advanced plagiarism detection using multiple databases including web content, academic papers, and proprietary sources with detailed similarity reports.', 'api', 'content-writing', 0.01, '🔍', ARRAY['plagiarism','originality','content','verification'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 920, 4.5, 'CheckText');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Color Palette Generator', 'color-palette-generator', 'AI-generated color schemes from text descriptions with hex codes and accessibility scoring.', 'Smart color palette generation based on mood, theme, or description with WCAG accessibility compliance checking and export formats.', 'api', 'image-generation', 0.01, '🎨', ARRAY['color','palette','design','accessibility'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 4890, 4.2, 'ColorAI');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Webhook Relay', 'webhook-relay', 'Forward and transform webhooks with filtering, retry logic, and payload modification.', 'Advanced webhook processing with payload transformation, filtering rules, retry mechanisms, and multi-destination forwarding.', 'api', 'automation', 0.01, '🔗', ARRAY['webhooks','relay','transformation','automation'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2560, 4.7, 'HookRelay');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Log Analyzer', 'log-analyzer', 'Parse and summarize log files with error detection and pattern recognition.', 'Intelligent log analysis with error detection, pattern recognition, anomaly detection, and automated summaries for troubleshooting.', 'cli', 'data-analysis', 0.01, '📊', ARRAY['logs','analysis','debugging','monitoring'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1750, 4.4, 'LogSense');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Dependency Auditor', 'dependency-auditor', 'Check npm, pip, and gem dependencies for known vulnerabilities and license issues.', 'Comprehensive dependency scanning for security vulnerabilities, license compliance, and outdated packages across multiple package managers.', 'cli', 'code-generation', 0.01, '🔒', ARRAY['security','dependencies','vulnerabilities','audit'], true, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 2890, 4.8, 'SecureCode');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Agent Memory Manager', 'agent-memory-manager', 'Persistent memory storage for agents with semantic search and context retrieval.', 'Advanced memory management system for AI agents with vector storage, semantic search, context management, and memory consolidation.', 'skill', 'automation', 0.01, '🧠', ARRAY['memory','agents','vector','semantic-search'], true, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 3670, 4.9, 'MemoryCore');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Workflow Orchestrator', 'workflow-orchestrator', 'Chain multiple skills together into complex workflows with conditional logic and error handling.', 'Advanced workflow engine that chains multiple Agent Bazaar skills together with conditional branching, error handling, and parallel execution.', 'skill', 'automation', 0.01, '⚙️', ARRAY['workflow','orchestration','automation','skills'], false, 'free', false, '0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906', 1290, 4.6, 'FlowMaster');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('1Password CLI', '1password-cli', 'Password & secrets management via 1Password CLI. Secure credential storage and retrieval for agents.', 'Secure password and secrets management through 1Password CLI integration. Provides safe credential storage, retrieval, and management for agent workflows requiring authentication.', 'cli', 'security', 0.01, '🔑', ARRAY['passwords','secrets','security','cli'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 456, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Apple Reminders', 'apple-reminders', 'Manage Apple Reminders with full CRUD operations. List, add, edit, complete, and delete reminders across all lists.', 'Complete Apple Reminders integration with full CRUD operations. Agents can create, read, update, and delete reminders across all lists with native macOS integration.', 'cli', 'automation', 0.01, '🍎', ARRAY['apple','reminders','productivity','tasks'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 623, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Bear Notes', 'bear-notes', 'Create, search, and manage Bear notes seamlessly. Full note management with tag support and markdown formatting.', 'Comprehensive Bear notes integration with creation, search, and management capabilities. Supports markdown formatting, tags, and full-text search across all notes.', 'skill', 'automation', 0.01, '🐻', ARRAY['notes','bear','markdown','productivity'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 534, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Blog Watcher', 'blogwatcher', 'Monitor blogs and RSS/Atom feeds for updates. Automated content monitoring with change detection and alerts.', 'Automated blog and RSS/Atom feed monitoring with intelligent change detection. Tracks content updates, new posts, and changes with customizable alert mechanisms.', 'skill', 'data-analysis', 0.01, '📡', ARRAY['rss','monitoring','feeds','content'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 342, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('BluOS Controller', 'bluos-controller', 'BluOS speaker discovery, playback control, grouping, and volume management. Complete multiroom audio control.', 'Professional BluOS ecosystem control with automatic speaker discovery, playback management, multi-room grouping, and volume control across all connected devices.', 'skill', 'automation', 0.01, '🎵', ARRAY['bluos','audio','speakers','multiroom'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 278, 4.4, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('BlueBubbles iMessage', 'bluebubbles-imessage', 'Send and manage iMessages via BlueBubbles server. Full iMessage automation with attachment support.', 'Complete iMessage automation through BlueBubbles server integration. Send messages, manage conversations, handle attachments, and automate messaging workflows.', 'skill', 'automation', 0.01, '💬', ARRAY['imessage','messaging','bluebubbles','communication'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 567, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Camera Capture', 'camera-capture', 'Capture frames or clips from RTSP/ONVIF security cameras. Professional surveillance integration for agents.', 'Professional security camera integration with RTSP and ONVIF protocol support. Capture frames, record clips, and integrate surveillance footage into agent workflows.', 'skill', 'automation', 0.01, '📹', ARRAY['camera','rtsp','onvif','surveillance'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 432, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('ClawHub CLI', 'clawhub-cli', 'Search, install, update, and publish agent skills from ClawHub marketplace. Complete skill lifecycle management.', 'Complete ClawHub marketplace integration with search, installation, updates, and publishing capabilities. Manage the entire skill lifecycle from discovery to deployment.', 'cli', 'automation', 0.01, '🛠️', ARRAY['clawhub','skills','marketplace','cli'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 789, 4.9, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Eight Sleep Controller', 'eightctl-sleep', 'Control Eight Sleep pods with temperature adjustment, alarms, and schedule management. Smart mattress automation.', 'Smart mattress control for Eight Sleep pods with temperature regulation, alarm management, and sleep schedule automation. Optimize sleep environment automatically.', 'skill', 'automation', 0.01, '🛏️', ARRAY['sleep','eight-sleep','temperature','smart-home'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 298, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Gemini CLI', 'gemini-cli', 'Gemini AI for one-shot Q&A, summaries, and content generation. Direct Google AI integration for agents.', 'Direct integration with Google''s Gemini AI for question answering, content summarization, and text generation. Powerful AI capabilities for diverse agent workflows.', 'cli', 'content-writing', 0.01, '♊', ARRAY['gemini','ai','google','generation'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 645, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('GIF Search', 'gif-search', 'Search GIF providers, download results, and extract stills or sprite sheets. Complete GIF workflow automation.', 'Comprehensive GIF search and processing with provider integration, download capabilities, and frame extraction. Create sprite sheets and still images from animated GIFs.', 'skill', 'image-generation', 0.01, '🎞️', ARRAY['gif','search','animation','media'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 512, 4.3, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Google Workspace', 'google-workspace', 'Gmail, Calendar, Drive, Contacts, Sheets, and Docs CLI integration. Complete Google Workspace automation.', 'Comprehensive Google Workspace integration covering Gmail, Calendar, Drive, Contacts, Sheets, and Docs. Full productivity suite automation for enterprise agent workflows.', 'cli', 'automation', 0.01, '📧', ARRAY['google','workspace','gmail','productivity'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 723, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Google Places', 'google-places', 'Query Google Places API for text search, place details, and reviews. Location intelligence for agents.', 'Professional Google Places API integration with comprehensive search capabilities, detailed place information, reviews, and location intelligence for geospatial agent workflows.', 'api', 'data-analysis', 0.01, '📍', ARRAY['google','places','location','search'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 467, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Himalaya Email', 'himalaya-email', 'CLI email management via IMAP/SMTP with full message lifecycle support. List, read, write, reply, and search.', 'Complete email management through IMAP/SMTP protocols with full message lifecycle support including listing, reading, writing, replying, and searching across accounts.', 'cli', 'automation', 0.01, '📮', ARRAY['email','imap','smtp','cli'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 389, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('iMessage CLI', 'imessage-cli', 'iMessage/SMS CLI for listing chats, message history, real-time watching, and sending. Native macOS integration.', 'Native macOS iMessage and SMS integration with chat listing, message history access, real-time monitoring, and sending capabilities through command line interface.', 'cli', 'automation', 0.01, '💭', ARRAY['imessage','sms','macos','messaging'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 598, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Local Places Search', 'local-places-search', 'Search for nearby restaurants, cafes, and businesses via Google Places proxy. Local discovery for agents.', 'Local business discovery through Google Places proxy with restaurant, cafe, and business search capabilities. Perfect for location-aware agent applications.', 'skill', 'data-analysis', 0.01, '🏪', ARRAY['local','places','restaurants','search'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 356, 4.4, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('MCP Porter', 'mcp-porter', 'List, configure, authenticate, and call MCP servers/tools directly. Model Context Protocol integration for agents.', 'Advanced Model Context Protocol (MCP) integration with server listing, configuration management, authentication, and direct tool calling capabilities for enhanced agent interoperability.', 'skill', 'automation', 0.01, '🔌', ARRAY['mcp','protocol','tools','integration'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 234, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Model Usage Tracker', 'model-usage-tracker', 'Summarize per-model usage and costs for Codex/Claude. AI spending analytics and optimization insights.', 'Comprehensive AI model usage analytics and cost tracking for Codex, Claude, and other models. Provides spending insights, usage patterns, and optimization recommendations.', 'skill', 'data-analysis', 0.01, '📊', ARRAY['usage','tracking','costs','analytics'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 445, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Nano Banana Image', 'nano-banana-image', 'Generate or edit images via Gemini 3 Pro Image. Advanced AI image creation and manipulation.', 'Advanced image generation and editing powered by Gemini 3 Pro Image model. Create, modify, and enhance images with sophisticated AI-driven visual processing capabilities.', 'api', 'image-generation', 0.01, '🖼️', ARRAY['image','generation','gemini','ai'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 567, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Nano PDF Editor', 'nano-pdf-editor', 'Edit PDFs with natural-language instructions. AI-powered document manipulation and content modification.', 'AI-powered PDF editing with natural language instructions. Modify document content, structure, and formatting through intelligent document manipulation capabilities.', 'skill', 'automation', 0.01, '📝', ARRAY['pdf','editing','documents','ai'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 323, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Notion API', 'notion-api', 'Notion API integration for pages, databases, and blocks. Complete workspace automation and content management.', 'Complete Notion workspace integration with full API access to pages, databases, and blocks. Automate content management, data organization, and collaborative workflows.', 'api', 'automation', 0.01, '📓', ARRAY['notion','database','pages','productivity'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 689, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Obsidian Vault', 'obsidian-vault', 'Work with Obsidian vaults and automate note management via CLI. Knowledge graph automation for agents.', 'Comprehensive Obsidian vault management with CLI automation for notes, links, and knowledge graph operations. Perfect for knowledge management workflows and PKM systems.', 'cli', 'automation', 0.01, '🔮', ARRAY['obsidian','notes','vault','knowledge'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 412, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('OpenAI Image Generator', 'openai-image-gen', 'Batch-generate images via OpenAI Images API with gallery management. High-volume image creation workflow.', 'High-volume image generation through OpenAI Images API with batch processing, gallery management, and workflow automation for large-scale visual content creation.', 'api', 'image-generation', 0.01, '🎨', ARRAY['openai','images','batch','generation'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 634, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('OpenAI Whisper Local', 'openai-whisper-local', 'Local speech-to-text with Whisper CLI requiring no API key. Offline transcription for privacy-focused agents.', 'Privacy-focused local speech-to-text using OpenAI Whisper CLI without API requirements. Offline transcription for sensitive audio processing workflows.', 'cli', 'voice-audio', 0.01, '🎧', ARRAY['whisper','local','transcription','offline'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 478, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('OpenAI Whisper API', 'openai-whisper-api', 'Transcribe audio via OpenAI Whisper API with cloud processing. High-accuracy speech recognition service.', 'Cloud-based speech recognition through OpenAI Whisper API with high-accuracy transcription, multi-language support, and professional audio processing capabilities.', 'api', 'voice-audio', 0.01, '🗣️', ARRAY['whisper','api','transcription','openai'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 567, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Philips Hue', 'philips-hue', 'Control Philips Hue lights and scenes via OpenHue CLI. Complete smart lighting automation for agents.', 'Complete smart lighting control for Philips Hue systems with scene management, color control, and automation through OpenHue CLI integration.', 'skill', 'automation', 0.01, '💡', ARRAY['hue','lights','smart-home','automation'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 389, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Oracle CLI', 'oracle-cli', 'Prompt bundling with file context, AI engines, and session management. Advanced AI inference orchestration.', 'Advanced AI inference orchestration with prompt bundling, file context integration, multiple AI engines, and session management for complex reasoning workflows.', 'cli', 'content-writing', 0.01, '🔮', ARRAY['oracle','ai','inference','prompting'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 345, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Foodora Orders', 'foodora-orders', 'Check past orders and active order status from Foodora delivery service. Food delivery tracking automation.', 'Food delivery tracking and order management for Foodora with historical order access and active delivery status monitoring for meal planning automation.', 'skill', 'automation', 0.01, '🍔', ARRAY['foodora','orders','delivery','food'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 267, 4.3, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Peekaboo macOS', 'peekaboo-macos', 'Capture and automate macOS UI interactions with screen recording and control. Native macOS automation for agents.', 'Native macOS UI automation with screen capture, recording, and interaction control. Perfect for desktop automation workflows and UI testing scenarios.', 'skill', 'automation', 0.01, '🖥️', ARRAY['macos','ui','automation','screen'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 423, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('ElevenLabs TTS', 'elevenlabs-tts', 'ElevenLabs text-to-speech with natural, expressive voices. Premium voice synthesis for agent communication.', 'Premium text-to-speech synthesis using ElevenLabs'' natural and expressive voice models. High-quality voice generation for agent communication and content creation.', 'api', 'voice-audio', 0.01, '🎙️', ARRAY['elevenlabs','tts','voice','synthesis'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 734, 4.9, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Session Log Search', 'session-log-search', 'Search and analyze your own conversation and session logs. Historical context retrieval for agent continuity.', 'Advanced session log search and analysis for conversation history and context retrieval. Enables agent continuity through historical interaction analysis.', 'skill', 'data-analysis', 0.01, '🔍', ARRAY['logs','search','sessions','history'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 356, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Sherpa TTS Local', 'sherpa-tts-local', 'Local text-to-speech via sherpa-onnx with offline processing and no cloud dependencies. Privacy-first TTS.', 'Privacy-focused local text-to-speech using sherpa-onnx with completely offline processing and no cloud dependencies for secure voice synthesis.', 'skill', 'voice-audio', 0.01, '🔊', ARRAY['sherpa','tts','local','offline'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 298, 4.4, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Slack Controller', 'slack-controller', 'Control Slack with reactions, pinning, unpinning, and channel/DM management. Complete Slack workspace automation.', 'Comprehensive Slack workspace automation with message reactions, content pinning, channel management, and DM control for complete team communication workflow.', 'skill', 'automation', 0.01, '💬', ARRAY['slack','messaging','workspace','automation'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 512, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Songsee Audio Viz', 'songsee-audio-viz', 'Generate spectrograms and feature-panel visualizations from audio files. Audio analysis and visualization for agents.', 'Advanced audio analysis and visualization with spectrogram generation and feature-panel visualizations for comprehensive audio content analysis and processing.', 'skill', 'image-generation', 0.01, '📊', ARRAY['audio','visualization','spectrograms','analysis'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 234, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Sonos Controller', 'sonos-controller', 'Control Sonos speakers with discovery, playback, volume, and grouping. Multiroom audio management for smart homes.', 'Professional Sonos ecosystem control with automatic speaker discovery, playback management, volume control, and multiroom grouping for comprehensive smart home audio.', 'skill', 'automation', 0.01, '🔊', ARRAY['sonos','speakers','multiroom','audio'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 445, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Spotify Player', 'spotify-player', 'Terminal Spotify playback control and music search. Complete Spotify automation from command line.', 'Full Spotify integration with terminal-based playback control, music search, playlist management, and automation capabilities for command-line music workflows.', 'cli', 'automation', 0.01, '🎵', ARRAY['spotify','music','playback','terminal'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 623, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('URL Summarizer', 'url-summarizer', 'Summarize or extract text from URLs, podcasts, and local files. AI-powered content analysis and extraction.', 'AI-powered content analysis and summarization for URLs, podcasts, and local files with intelligent text extraction and comprehensive content processing capabilities.', 'skill', 'content-writing', 0.01, '📖', ARRAY['summarize','url','podcasts','extraction'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 567, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Things Mac', 'things-mac', 'Manage Things 3 tasks, inbox, and projects via CLI. Native macOS task management automation.', 'Native macOS task management through Things 3 integration with full CLI control over tasks, inbox management, project organization, and productivity workflows.', 'cli', 'automation', 0.01, '✅', ARRAY['things','tasks','macos','productivity'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 389, 4.6, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('tmux Controller', 'tmux-controller', 'Remote-control tmux sessions with keystroke injection and pane scraping. Terminal session automation for developers.', 'Advanced tmux session automation with remote control capabilities, keystroke injection, pane content scraping, and comprehensive terminal session management for developers.', 'skill', 'automation', 0.01, '💻', ARRAY['tmux','terminal','sessions','automation'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 267, 4.5, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Trello API', 'trello-api', 'Manage Trello boards, lists, and cards via REST API. Complete project management automation for agents.', 'Complete Trello integration with REST API access for board management, list organization, card manipulation, and comprehensive project management automation workflows.', 'api', 'automation', 0.01, '📋', ARRAY['trello','boards','cards','project-management'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 456, 4.7, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Video Frame Extract', 'video-frame-extract', 'Extract frames or clips from videos using ffmpeg. Video processing and frame analysis for content workflows.', 'Professional video processing with ffmpeg integration for frame extraction, clip creation, and video analysis workflows for content processing and media automation.', 'skill', 'image-generation', 0.01, '🎬', ARRAY['video','frames','ffmpeg','extraction'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 334, 4.4, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('Voice Call', 'voice-call', 'Start voice calls via OpenClaw voice-call plugin. Real-time voice communication integration for agents.', 'Real-time voice communication capabilities through OpenClaw voice-call plugin integration with call initiation and management for interactive agent experiences.', 'skill', 'automation', 0.01, '📞', ARRAY['voice','calls','communication','real-time'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 289, 4.8, 'clawhub-community');
INSERT INTO capabilities (name, slug, description, long_description, type, category, price_per_call, icon, tags, featured, listing_tier, verified, provider_wallet, usage_count, rating, provider_name)
VALUES ('WhatsApp CLI', 'whatsapp-cli', 'Send WhatsApp messages and search/sync message history. Complete WhatsApp automation via command line.', 'Complete WhatsApp automation with command-line message sending, history search, message synchronization, and comprehensive messaging workflow management.', 'cli', 'automation', 0.01, '📱', ARRAY['whatsapp','messaging','cli','automation'], false, 'free', false, '0xAa41DE518042eB5801081fA6580cFb7326162fe8', 578, 4.6, 'clawhub-community');

-- Seeded 114 capabilities
