import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const SKILL_CONFIG = {
  priceUsd: 0.03,
  payTo: process.env.X402_WALLET_ADDRESS || "0x0000000000000000000000000000000000000000",
  networks: ["base"],
  tokens: ["USDC"],
  capabilityId: "ai-content-writer",
  description: "AI content generation — blog posts, social media, marketing copy, SEO articles",
};

function getSupabase() {
  return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
}

export async function POST(request: Request) {
  const start = Date.now();
  const paymentHeader = request.headers.get("x-402-payment") || request.headers.get("x-payment-token");

  if (!paymentHeader) {
    return NextResponse.json({
      status: 402,
      message: "Payment required. Send USDC on Base to use this skill.",
      payment: SKILL_CONFIG,
      howToPay: {
        step1: `Send $${SKILL_CONFIG.priceUsd} USDC to ${SKILL_CONFIG.payTo} on Base`,
        step2: "Include the transaction hash in the X-402-Payment header",
        step3: "Resend your request",
      },
    }, { status: 402 });
  }

  // Verify payment (allow demo/test tokens)
  const isDemoToken = paymentHeader === "demo" || paymentHeader === "test";
  if (!isDemoToken) {
    try {
      const verifyRes = await fetch(new URL("/api/x402/verify", request.url).toString(), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ txHash: paymentHeader, capabilityId: SKILL_CONFIG.capabilityId }),
      });
      const verifyData = await verifyRes.json();
      if (!verifyData.verified) {
        return NextResponse.json({ status: 402, error: "Payment verification failed", details: verifyData.error }, { status: 402 });
      }
    } catch {
      return NextResponse.json({ error: "Payment verification service unavailable" }, { status: 503 });
    }
  }

  let body;
  try { body = await request.json(); } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { prompt, type = "blog", tone = "professional", length = "medium" } = body;
  if (!prompt) {
    return NextResponse.json({ error: "prompt field is required" }, { status: 400 });
  }

  const lengthGuide: Record<string, string> = {
    short: "150-300 words",
    medium: "500-800 words",
    long: "1000-1500 words",
  };

  let content;
  const openaiKey = process.env.OPENAI_API_KEY;

  if (openaiKey && openaiKey !== "sk-placeholder") {
    try {
      const openaiRes = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${openaiKey}` },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            {
              role: "system",
              content: `You are an expert content writer. Write ${type} content with a ${tone} tone. Target length: ${lengthGuide[length] || "500-800 words"}. Return JSON with: "title" (string), "content" (string with markdown), "summary" (1-2 sentences), "seoKeywords" (array of 5-8 keywords), "readingTimeMin" (number). Return ONLY valid JSON.`,
            },
            { role: "user", content: prompt },
          ],
          temperature: 0.7,
          max_tokens: 3000,
        }),
      });
      const data = await openaiRes.json();
      content = JSON.parse(data.choices?.[0]?.message?.content);
    } catch {
      content = generateBasicContent(prompt, type, tone);
    }
  } else {
    content = generateBasicContent(prompt, type, tone);
  }

  const latencyMs = Date.now() - start;

  try {
    const supabase = getSupabase();
    await supabase.from("usage_logs").insert({
      capability_id: SKILL_CONFIG.capabilityId,
      payer_address: paymentHeader,
      payment_tx: paymentHeader,
      amount_usd: SKILL_CONFIG.priceUsd,
      latency_ms: latencyMs,
      success: true,
    });
  } catch {}

  return NextResponse.json({
    success: true,
    content,
    metadata: {
      skill: "ai-content-writer",
      version: "1.0.0",
      latencyMs,
      billedAmount: SKILL_CONFIG.priceUsd,
      engine: openaiKey && openaiKey !== "sk-placeholder" ? "gpt-4o-mini" : "template",
    },
  });
}

function generateBasicContent(prompt: string, type: string, tone: string) {
  const title = `${prompt.slice(0, 60)}${prompt.length > 60 ? "..." : ""}`;
  return {
    title,
    content: `# ${title}\n\nThis is a ${tone} ${type} about: ${prompt}\n\n## Key Points\n\n- AI-generated content based on your prompt\n- Optimized for ${type} format\n- Written in a ${tone} tone\n\n## Summary\n\n${prompt}\n\n---\n*Generated by Agent Bazaar Content Writer*`,
    summary: `A ${tone} ${type} covering: ${prompt.slice(0, 100)}`,
    seoKeywords: prompt.toLowerCase().split(" ").filter(w => w.length > 3).slice(0, 6),
    readingTimeMin: 2,
  };
}
