// ── Capability Types ──

/**
 * Type classification for capabilities in the Agent Bazaar ecosystem.
 * - "api": HTTP REST API endpoints
 * - "cli": Command-line interface tools  
 * - "skill": Integrated agent skills/functions
 */
export type CapabilityType = "api" | "cli" | "skill";

/**
 * Category classification for organizing and discovering capabilities.
 * Used for filtering and browsing capabilities by domain/use case.
 */
export type CapabilityCategory =
  | "code-generation"    // Code writing, review, refactoring
  | "image-generation"   // AI image creation and manipulation
  | "data-analysis"      // Data processing and insights
  | "content-writing"    // Text generation and editing
  | "web-scraping"       // Data extraction from websites
  | "trading"            // Financial and crypto trading
  | "research"           // Information gathering and analysis
  | "automation"         // Task automation and workflows
  | "devops"             // Development and operations tools
  | "media";             // Audio, video, and multimedia processing

/**
 * Complete specification of a paid capability in the Agent Bazaar registry.
 * 
 * Represents a discoverable service that can be invoked by AI agents
 * and other consumers through the x402 payment protocol.
 */
export interface Capability {
  /** Unique identifier generated by the registry */
  id: string;
  /** Human-readable display name */
  name: string;
  /** URL-friendly identifier (lowercase, hyphens) */
  slug: string;
  /** Brief description for discovery and listings */
  description: string;
  /** Detailed description with usage instructions and examples */
  longDescription: string;
  /** Classification of capability interface type */
  type: CapabilityType;
  /** Domain/use-case category for organization */
  category: CapabilityCategory;
  /** Price in USD for each capability invocation */
  pricePerCall: number;
  /** HTTP endpoint that implements the x402 payment protocol */
  x402Endpoint: string;
  /** URL to capability icon/logo for display */
  icon: string;
  /** Average user rating (0-5 scale, calculated by registry) */
  rating: number;
  /** Total number of successful invocations (tracked by registry) */
  usageCount: number;
  /** Whether this capability is featured in registry listings */
  featured: boolean;
  /** Searchable tags for discovery and filtering */
  tags: string[];
  /** Display name of the capability creator/provider */
  creatorName: string;
}

// ── Payment Types ──

/**
 * Payment requirements and details returned in 402 responses.
 * 
 * Contains all information needed for a client to understand
 * payment requirements and complete a transaction.
 */
export interface PaymentInfo {
  /** Price in USD for a single call */
  priceUsd: number;
  /** Crypto address to send payment to */
  payTo: string;
  /** Supported blockchain networks (e.g. "base", "ethereum", "polygon") */
  networks: string[];
  /** Supported payment tokens (e.g. "USDC", "ETH", "MATIC") */
  tokens: string[];
  /** Human-readable description of what the payment is for */
  description: string;
  /** Unique identifier of the capability requiring payment */
  capabilityId: string;
}

/**
 * Payment proof token provided by clients to authenticate payment.
 * 
 * Represents either a transaction hash, signed payment proof, or
 * other cryptographic evidence of payment completion.
 */
export interface PaymentToken {
  /** Signed payment proof, transaction hash, or payment identifier */
  token: string;
  /** Blockchain network where payment was made */
  network: string;
  /** Payment amount in the smallest unit (e.g. wei, satoshis) */
  amount: string;
  /** Wallet address that made the payment */
  payer: string;
}

/**
 * Standard 402 Payment Required HTTP response structure.
 * 
 * Returned by x402-protected endpoints when no valid payment
 * token is provided or payment validation fails.
 */
export interface X402Response {
  /** HTTP status code (always 402) */
  status: 402;
  /** Detailed payment requirements and information */
  payment: PaymentInfo;
}

// ── Usage / Stats ──

/**
 * Individual usage record for tracking capability invocations.
 * 
 * Captured by the x402 middleware for each request to provide
 * analytics and monitoring data to capability providers.
 */
export interface UsageRecord {
  /** Unique identifier of the capability that was called */
  capabilityId: string;
  /** Unix timestamp (milliseconds) when the request was made */
  timestamp: number;
  /** Response time in milliseconds for the request */
  latencyMs: number;
  /** Whether the request completed successfully (HTTP 2xx) */
  success: boolean;
  /** Wallet address of the payer (if available) */
  payer?: string;
  /** Amount paid for this request in USD */
  amountUsd: number;
}

/**
 * Aggregated statistics and performance metrics for a capability.
 * 
 * Provides insights into usage patterns, performance, and revenue
 * for capability providers to monitor their services.
 */
export interface CapabilityStats {
  /** Unique identifier of the capability */
  capabilityId: string;
  /** Total number of successful calls since registration */
  totalCalls: number;
  /** Success rate as a decimal (0.0 to 1.0) */
  successRate: number;
  /** Average response time in milliseconds across all calls */
  avgLatencyMs: number;
  /** Total revenue generated in USD */
  totalRevenueUsd: number;
  /** Number of calls in the last 24 hours */
  last24hCalls: number;
}

// ── Middleware Config ──

/**
 * Configuration options for the x402 payment middleware.
 * 
 * Defines pricing, payment validation, and callback behavior
 * for protecting API endpoints with micropayment requirements.
 */
export interface X402MiddlewareConfig {
  /** Price per API call in USD */
  priceUsd: number;
  /** Cryptocurrency wallet address to receive payments */
  payTo: string;
  /** Supported blockchain networks (defaults to ["base"]) */
  networks?: string[];
  /** Supported payment tokens (defaults to ["USDC"]) */
  tokens?: string[];
  /** Unique capability identifier for analytics tracking */
  capabilityId?: string;
  /** Human-readable description shown in 402 payment responses */
  description?: string;
  /** Custom function to validate payment tokens (defaults to basic validation) */
  validatePayment?: (token: PaymentToken) => Promise<boolean>;
  /** Callback invoked after successful payment validation */
  onPayment?: (token: PaymentToken, req: unknown) => void;
}

// ── Client Config ──

/**
 * Configuration options for the X402Client.
 * 
 * Defines registry connection, default payment credentials,
 * and wallet integration for automatic payment signing.
 */
export interface X402ClientConfig {
  /** Base URL of the Agent Bazaar registry API (defaults to production) */
  registryUrl?: string;
  /** Default payment token to attach to all requests */
  paymentToken?: string;
  /** Wallet configuration for automatic payment signing and transactions */
  wallet?: {
    /** Wallet address for payment identification */
    address: string;
    /** Async function to sign payment messages/proofs */
    sign: (message: string) => Promise<string>;
  };
}
