import { Capability, Review } from "@/types";

export const CATEGORIES = [
  { value: "code-generation", label: "Code Generation", icon: "💻" },
  { value: "image-generation", label: "Image Generation", icon: "🎨" },
  { value: "data-analysis", label: "Data Analysis", icon: "📊" },
  { value: "content-writing", label: "Content Writing", icon: "✍️" },
  { value: "web-scraping", label: "Web Scraping", icon: "🕸️" },
  { value: "trading", label: "Trading", icon: "📈" },
  { value: "research", label: "Research", icon: "🔬" },
  { value: "automation", label: "Automation", icon: "⚙️" },
] as const;

export const CAPABILITIES: Capability[] = [
  {
    id: "1",
    name: "GPT-4 Code Review",
    slug: "gpt4-code-review",
    description: "Automated code review via GPT-4. Submit a diff, get security analysis, bug detection, and style suggestions.",
    longDescription: "Production-grade code review powered by GPT-4. Catches security vulnerabilities, logic bugs, and style violations in any language.",
    type: "api",
    category: "code-generation",
    pricePerCall: 0.05,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/code-review",
    icon: "🔍",
    rating: 4.9,
    usageCount: 284000,
    featured: true,
    tags: ["code-review", "security", "gpt-4", "developer"],
    creatorName: "DevForge",
    listingTier: "spotlight",
  },
  {
    id: "2",
    name: "DALL-E Image Generator",
    slug: "dalle-image-gen",
    description: "Generate images from text prompts. x402-enabled — agents can generate images autonomously.",
    longDescription: "High-quality image generation via DALL-E 3. Supports all aspect ratios, styles, and quality levels.",
    type: "api",
    category: "image-generation",
    pricePerCall: 0.08,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/image-gen",
    icon: "🎨",
    rating: 4.7,
    usageCount: 512000,
    featured: true,
    tags: ["image", "dalle", "generation", "creative"],
    creatorName: "PixelMint",
    listingTier: "spotlight",
  },
  {
    id: "3",
    name: "Web Scraper API",
    slug: "web-scraper-api",
    description: "Extract structured data from any URL. Handles JS-rendered pages, anti-bot, and pagination.",
    longDescription: "Enterprise-grade web scraping. Returns clean JSON from any webpage with automatic anti-detection.",
    type: "api",
    category: "web-scraping",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/scraper",
    icon: "🕸️",
    rating: 4.6,
    usageCount: 1340000,
    featured: true,
    tags: ["scraping", "web", "data", "extraction"],
    creatorName: "CrawlLab",
  },
  {
    id: "4",
    name: "SEO Analyzer",
    slug: "seo-analyzer",
    description: "Full SEO audit for any URL. Technical SEO, content scoring, keyword gaps, and competitor analysis.",
    longDescription: "Comprehensive SEO analysis returning actionable recommendations. Covers on-page, technical, and content optimization.",
    type: "api",
    category: "content-writing",
    pricePerCall: 0.10,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/seo-audit",
    icon: "📈",
    rating: 4.8,
    usageCount: 89000,
    featured: true,
    tags: ["seo", "marketing", "analysis", "content"],
    creatorName: "RankForge",
    listingTier: "featured",
  },
  {
    id: "5",
    name: "SQL Query Generator",
    slug: "sql-query-gen",
    description: "Natural language to SQL. Supports PostgreSQL, MySQL, SQLite, and BigQuery dialects.",
    longDescription: "Describe what you need in English, get production-ready SQL. Handles complex joins, CTEs, and window functions.",
    type: "api",
    category: "code-generation",
    pricePerCall: 0.03,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/sql-gen",
    icon: "🗄️",
    rating: 4.5,
    usageCount: 167000,
    featured: false,
    tags: ["sql", "database", "query", "natural-language"],
    creatorName: "QueryCraft",
  },
  {
    id: "6",
    name: "git-audit CLI",
    slug: "git-audit-cli",
    description: "CLI tool that audits your git history for secrets, large files, and compliance issues.",
    longDescription: "Install via npm/brew. Scans entire git history for leaked credentials, oversized binaries, and policy violations.",
    type: "cli",
    category: "code-generation",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/git-audit",
    icon: "🔐",
    rating: 4.8,
    usageCount: 45000,
    featured: false,
    tags: ["git", "security", "cli", "audit"],
    creatorName: "SecureDev",
  },
  {
    id: "7",
    name: "CSV Intelligence",
    slug: "csv-intelligence",
    description: "Upload a CSV, ask questions in natural language. Returns charts, stats, and insights.",
    longDescription: "Data analysis without code. Upload any CSV and get instant statistical analysis, visualizations, and AI-powered insights.",
    type: "api",
    category: "data-analysis",
    pricePerCall: 0.06,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/csv-intel",
    icon: "📊",
    rating: 4.4,
    usageCount: 73000,
    featured: false,
    tags: ["csv", "analytics", "data", "visualization"],
    creatorName: "DataPilot",
  },
  {
    id: "8",
    name: "Blog Post Writer",
    slug: "blog-post-writer",
    description: "Generate SEO-optimized long-form blog posts. Includes outline, meta tags, and internal linking suggestions.",
    longDescription: "Feed it a keyword and tone, get a publish-ready blog post with SEO optimization baked in.",
    type: "api",
    category: "content-writing",
    pricePerCall: 0.15,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/blog-writer",
    icon: "✍️",
    rating: 4.7,
    usageCount: 198000,
    featured: true,
    tags: ["blog", "seo", "writing", "content"],
    creatorName: "ContentForge",
    listingTier: "featured",
  },
  {
    id: "9",
    name: "Crypto Price Oracle",
    slug: "crypto-price-oracle",
    description: "Real-time and historical crypto prices with technical indicators. Agent-native trading data.",
    longDescription: "Access real-time prices, OHLCV data, and 50+ technical indicators for any crypto pair. Built for trading agents.",
    type: "api",
    category: "trading",
    pricePerCall: 0.005,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/crypto-oracle",
    icon: "₿",
    rating: 4.6,
    usageCount: 2100000,
    featured: false,
    tags: ["crypto", "trading", "prices", "oracle"],
    creatorName: "ChainData",
  },
  {
    id: "10",
    name: "Research Summarizer",
    slug: "research-summarizer",
    description: "Summarize academic papers, reports, and documents. Returns structured key findings and citations.",
    longDescription: "Paste a URL or upload a PDF — get a structured summary with key findings, methodology, and citation-ready references.",
    type: "api",
    category: "research",
    pricePerCall: 0.04,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/research-summary",
    icon: "🔬",
    rating: 4.5,
    usageCount: 56000,
    featured: false,
    tags: ["research", "academic", "summary", "papers"],
    creatorName: "ScholarAI",
  },
  {
    id: "11",
    name: "deploy-cli",
    slug: "deploy-cli",
    description: "One-command deploy to any cloud. Supports Vercel, AWS, GCP, and Fly.io with zero config.",
    longDescription: "CLI tool that detects your framework and deploys to your preferred cloud provider with sensible defaults.",
    type: "cli",
    category: "automation",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/deploy-cli",
    icon: "🚀",
    rating: 4.3,
    usageCount: 34000,
    featured: false,
    tags: ["deploy", "cli", "cloud", "devops"],
    creatorName: "ShipFast",
  },
  {
    id: "12",
    name: "Email Composer Skill",
    slug: "email-composer-skill",
    description: "Agent skill for composing context-aware emails. Drop into any agent framework as a tool.",
    longDescription: "A composable skill that any AI agent can use. Given context and intent, drafts professional emails with proper tone.",
    type: "skill",
    category: "automation",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/email-compose",
    icon: "📧",
    rating: 4.6,
    usageCount: 127000,
    featured: false,
    tags: ["email", "skill", "agent", "automation"],
    creatorName: "ToolSmith",
  },
];

export const REVIEWS: Review[] = [
  { id: "r1", capabilityId: "1", userName: "DevAlex", rating: 5, comment: "Catches bugs my team misses. The x402 integration means my CI agent just pays per review automatically.", date: "2026-02-01" },
  { id: "r2", capabilityId: "3", userName: "DataHunter", rating: 5, comment: "Finally a scraper that handles SPAs. My research agent uses this autonomously now.", date: "2026-01-28" },
  { id: "r3", capabilityId: "8", userName: "ContentKing", rating: 5, comment: "30 blog posts last month, all page 1. My content agent calls this on autopilot.", date: "2026-02-05" },
  { id: "r4", capabilityId: "9", userName: "CryptoBot", rating: 4, comment: "Rock-solid oracle. My trading agent makes 50+ calls/day at $0.005 each. Incredible value.", date: "2026-02-10" },
];
