import { Capability, Review, Bundle } from "@/types";

export const CATEGORIES = [
  { value: "code-generation", label: "Code Generation", icon: "💻" },
  { value: "image-generation", label: "Image Generation", icon: "🎨" },
  { value: "data-analysis", label: "Data Analysis", icon: "📊" },
  { value: "content-writing", label: "Content Writing", icon: "✍️" },
  { value: "web-scraping", label: "Web Scraping", icon: "🕸️" },
  { value: "trading", label: "Trading", icon: "📈" },
  { value: "research", label: "Research", icon: "🔬" },
  { value: "automation", label: "Automation", icon: "⚙️" },
  { value: "security", label: "Security", icon: "🛡️" },
  { value: "testing", label: "Testing", icon: "🧪" },
  { value: "cicd", label: "CI/CD", icon: "🔄" },
  { value: "translation", label: "Translation", icon: "🌐" },
  { value: "voice-audio", label: "Voice & Audio", icon: "🎙️" },
  { value: "payments", label: "Payments", icon: "💳" },
  { value: "notifications", label: "Notifications", icon: "📱" },
  { value: "scheduling", label: "Scheduling", icon: "📅" },
] as const;

export const CAPABILITIES: Capability[] = [
  {
    id: "0",
    name: "AI Agent Builder",
    slug: "agent-builder",
    description: "Describe what you want. Get a complete, ready-to-run AI agent with personality, tools, cron jobs, and Agent Bazaar skill integrations.",
    longDescription: "The meta skill that creates agents. Describe your desired functionality in natural language and get a complete OpenClaw agent with SOUL.md, AGENTS.md, TOOLS.md, cron jobs, and Agent Bazaar skill integrations. Every agent created becomes a customer of Agent Bazaar skills — the ultimate flywheel.",
    type: "api",
    category: "automation",
    pricePerCall: 0.25,
    x402Endpoint: "https://agent-bazaar.com/api/x402/agent-builder",
    icon: "🤖",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["agent", "builder", "openclaw", "automation", "no-code"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "spotlight",
    mode: "natural",
  },

  {
    id: "1",
    name: "GPT-4 Code Review",
    slug: "gpt4-code-review",
    description: "Automated code review via GPT-4. Submit a diff, get security analysis, bug detection, and style suggestions.",
    longDescription: "Production-grade code review powered by GPT-4. Catches security vulnerabilities, logic bugs, and style violations in any language.",
    type: "api",
    category: "code-generation",
    pricePerCall: 0.05,
    x402Endpoint: "https://agent-bazaar.com/api/x402/code-review",
    icon: "🔍",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["code-review", "security", "gpt-4", "developer"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "spotlight",
    mode: ["structured", "natural"],
  },

  {
    id: "2",
    name: "DALL-E Image Generator",
    slug: "dalle-image-gen",
    description: "Generate images from text prompts. x402-enabled — agents can generate images autonomously.",
    longDescription: "High-quality image generation via DALL-E 3. Supports all aspect ratios, styles, and quality levels.",
    type: "api",
    category: "image-generation",
    pricePerCall: 0.08,
    x402Endpoint: "https://agent-bazaar.com/api/x402/dalle-image",
    icon: "🎨",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["image", "dalle", "generation", "creative"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "spotlight",
    mode: ["structured", "natural"],
  },

  {
    id: "3",
    name: "Web Scraper API",
    slug: "web-scraper-api",
    description: "Extract structured data from any URL. Handles JS-rendered pages, anti-bot, and pagination.",
    longDescription: "Enterprise-grade web scraping. Returns clean JSON from any webpage with automatic anti-detection.",
    type: "api",
    category: "web-scraping",
    pricePerCall: 0.02,
    x402Endpoint: "https://agent-bazaar.com/api/x402/web-scraper",
    icon: "🕸️",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["scraping", "web", "data", "extraction"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    mode: "natural",
  },

  {
    id: "4",
    name: "Blog Post Writer",
    slug: "blog-post-writer",
    description: "Generate SEO-optimized long-form blog posts. Includes outline, meta tags, and internal linking suggestions.",
    longDescription: "Feed it a keyword and tone, get a publish-ready blog post with SEO optimization baked in.",
    type: "api",
    category: "content-writing",
    pricePerCall: 0.15,
    x402Endpoint: "https://agent-bazaar.com/api/x402/content-writer",
    icon: "✍️",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["blog", "seo", "writing", "content"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },

  {
    id: "5",
    name: "Crypto Price Oracle",
    slug: "crypto-price-oracle",
    description: "Real-time and historical crypto prices with technical indicators. Agent-native trading data.",
    longDescription: "Access real-time prices, OHLCV data, and 50+ technical indicators for any crypto pair. Built for trading agents.",
    type: "api",
    category: "trading",
    pricePerCall: 0.005,
    x402Endpoint: "https://agent-bazaar.com/api/x402/defi-yield",
    icon: "₿",
    rating: 0,
    usageCount: 0,
    featured: false,
    tags: ["crypto", "trading", "prices", "oracle"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    mode: "structured",
  },

  {
    id: "6",
    name: "Research Summarizer",
    slug: "research-summarizer",
    description: "Summarize academic papers, reports, and documents. Returns structured key findings and citations.",
    longDescription: "Paste a URL or upload a PDF — get a structured summary with key findings, methodology, and citation-ready references.",
    type: "api",
    category: "research",
    pricePerCall: 0.04,
    x402Endpoint: "https://agent-bazaar.com/api/x402/research-summarizer",
    icon: "🔬",
    rating: 0,
    usageCount: 0,
    featured: false,
    tags: ["research", "academic", "summary", "papers"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    mode: "natural",
  },

  {
    id: "7",
    name: "Web Search Skill",
    slug: "web-search-skill",
    description: "Real-time web search for agents. Returns structured results with snippets and sources.",
    longDescription: "Drop-in web search capability for any agent framework. Returns ranked results with full page content extraction.",
    type: "skill",
    category: "research",
    pricePerCall: 0.005,
    x402Endpoint: "https://agent-bazaar.com/api/x402/web-search",
    icon: "🔎",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["search", "web", "skill", "agent", "research"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },

  {
    id: "8",
    name: "Smart Contract Auditor",
    slug: "smart-contract-auditor",
    description: "Automated smart contract security analysis. Detects reentrancy, overflow, and logic bugs in Solidity.",
    longDescription: "Professional smart contract auditing powered by Mythril and Slither. Identifies critical vulnerabilities before deployment.",
    type: "api",
    category: "security",
    pricePerCall: 0.18,
    x402Endpoint: "https://agent-bazaar.com/api/x402/smart-contract-audit",
    icon: "🔐",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["solidity", "audit", "smart-contract", "mythril", "security"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: ["structured", "natural"],
  },

  {
    id: "9",
    name: "World Model Simulation",
    slug: "world-model-simulation",
    description: "World Model as a Service: Run forward simulations of agent actions in uncertain environments. Input current state + proposed actions; output predicted outcomes, risks, confidence scores, and recommended next steps. Helps agents de-risk decisions before spending real resources.",
    longDescription: "Built with Claude for reliable long-term planning. Chainable — agents can call multiple times in workflows. Supports custom time horizons and scenario counts.",
    type: "api",
    category: "research",
    pricePerCall: 0.005,
    x402Endpoint: "https://agent-bazaar.com/api/x402/simulate",
    icon: "🌍",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["simulation", "planning", "risk", "world-model", "decision-making"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "spotlight",
    mode: "structured",
  },

  {
    id: "10",
    slug: "ai-video-generation",
    name: "AI Video Generation",
    description: "Generate AI videos from text prompts — supports 40+ models including Veo 3, Grok Video, and Seedance.",
    longDescription: "Text-to-video and image-to-video generation with configurable duration, aspect ratio, and style. Supports Veo 3, Grok Video, Seedance, Wan 2.5, and more. 1K+ installs/24h on skills.sh.",
    type: "api",
    category: "video-generation",
    pricePerCall: 0.20,
    x402Endpoint: "https://agent-bazaar.com/api/x402/video-generation",
    icon: "🎬",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["video", "ai", "generation", "veo", "grok", "creative", "media"],
    creatorName: "inference.sh (tul-sh)",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "structured",
  },

  {
    id: "11",
    slug: "twitter-automation",
    name: "Twitter/X Automation",
    description: "Automate Twitter/X — generate optimized tweets, threads, engagement strategies, and posting schedules.",
    longDescription: "Compose, schedule, and plan X/Twitter content with platform-specific best practices. Actions: compose-tweet, compose-thread, engagement-plan, schedule, analyze-profile. 1K+ installs/24h on skills.sh.",
    type: "api",
    category: "social-media",
    pricePerCall: 0.20,
    x402Endpoint: "https://agent-bazaar.com/api/x402/twitter-automation",
    icon: "🐦",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["twitter", "x", "social", "automation", "content", "marketing", "growth"],
    creatorName: "inference.sh (tul-sh)",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },

  {
    id: "12",
    slug: "background-removal",
    name: "Background Removal",
    description: "Remove backgrounds from images — product photos, portraits, e-commerce.",
    longDescription: "AI-powered segmentation returns transparent PNG, white JPG, or WebP output. Supports product photos, portraits, and batch processing. Trending on skills.sh.",
    type: "api",
    category: "image-generation",
    pricePerCall: 0.15,
    x402Endpoint: "https://agent-bazaar.com/api/x402/background-removal",
    icon: "✂️",
    rating: 0,
    usageCount: 0,
    featured: false,
    tags: ["image", "background", "removal", "processing", "ecommerce", "design"],
    creatorName: "inference.sh (tul-sh)",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "free",
    mode: "structured",
  },

  {
    id: "13",
    slug: "social-content-generator",
    name: "Social Media Content Generator",
    description: "Generate platform-specific social media content — X threads, Instagram captions, TikTok scripts, LinkedIn posts.",
    longDescription: "Each platform formatted with correct conventions, hashtags, and posting strategy. Supports multi-platform content from a single topic. 86 installs/hour on skills.sh.",
    type: "api",
    category: "social-media",
    pricePerCall: 0.15,
    x402Endpoint: "https://agent-bazaar.com/api/x402/social-content",
    icon: "📱",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["social", "content", "instagram", "tiktok", "linkedin", "marketing", "creator"],
    creatorName: "inference.sh (tul-sh)",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },

  {
    id: "14",
    slug: "web-search-api",
    name: "Web Search API",
    description: "Search the web programmatically — returns titles, URLs, snippets, and structured results.",
    longDescription: "Supports freshness filters, region targeting, and result count. Pairs with web-scraper for full research workflows. Uses Brave Search API with GPT-4o-mini fallback. 126 installs/hour on skills.sh.",
    type: "api",
    category: "search",
    pricePerCall: 0.10,
    x402Endpoint: "https://agent-bazaar.com/api/x402/web-search",
    icon: "🔍",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["search", "web", "research", "data", "discovery", "scraping"],
    creatorName: "inference.sh (tul-sh)",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "structured",
  },

  {
    id: "15",
    name: "Polymarket Intelligence",
    slug: "polymarket-intelligence",
    description: "AI-powered prediction market analysis — discover markets, analyze odds, get betting recommendations, and track trending markets on Polymarket.",
    longDescription: "Natural language interface to prediction markets. Ask anything — 'find interesting election markets', 'what are the odds on the Fed rate decision', 'which markets are mispriced right now'. Returns structured analysis with odds, volume, value assessments, and risk ratings. Supports discovery, analysis, recommendations, and trending market tracking.",
    type: "api",
    category: "trading",
    pricePerCall: 0.05,
    x402Endpoint: "https://agent-bazaar.com/api/x402/polymarket",
    icon: "🔮",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["polymarket", "predictions", "betting", "odds", "markets"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
];

// Alias for backwards compatibility
export const AGENTS = CAPABILITIES;

export const BUNDLES: Bundle[] = [
  {
    id: "b1",
    name: "Developer Skills Pack",
    description: "Everything a coding agent needs: code review, SQL generation, git auditing, and one-command deploys. Ship faster with AI assistance on every step.",
    price: 7,
    originalPrice: 19,
    atlasHint: "⚡ Atlas-ready — these skills run automatically in your dev workflows.",
    agents: [
      { id: "1", name: "GPT-4 Code Review", slug: "gpt4-code-review", icon: "🔍", originalPrice: 5 },
      { id: "5", name: "SQL Query Generator", slug: "sql-query-gen", icon: "🗄️", originalPrice: 3 },
      { id: "6", name: "git-audit CLI", slug: "git-audit-cli", icon: "🔐", originalPrice: 4 },
      { id: "11", name: "deploy-cli", slug: "deploy-cli", icon: "🚀", originalPrice: 7 },
    ],
  },
  {
    id: "b2",
    name: "Content & Research Pack",
    description: "Your content agent's full toolkit: write blog posts, audit SEO, scrape sources, and summarize research — all on autopilot via x402.",
    price: 9,
    originalPrice: 29,
    atlasHint: "✍️ Pair with Atlas to run a fully automated content pipeline.",
    agents: [
      { id: "8", name: "Blog Post Writer", slug: "blog-post-writer", icon: "✍️", originalPrice: 8 },
      { id: "4", name: "SEO Analyzer", slug: "seo-analyzer", icon: "📈", originalPrice: 10 },
      { id: "3", name: "Web Scraper API", slug: "web-scraper-api", icon: "🕸️", originalPrice: 5 },
      { id: "10", name: "Research Summarizer", slug: "research-summarizer", icon: "🔬", originalPrice: 6 },
    ],
  },
  {
    id: "b3",
    name: "Agent Infrastructure Pack",
    description: "Core infrastructure for any autonomous agent: persistent memory, real-time web search, email composition, and task scheduling — all x402-native.",
    price: 12,
    originalPrice: 35,
    atlasHint: "🧠 The foundation layer for production-grade Atlas agents.",
    agents: [
      { id: "13", name: "Memory Store Skill", slug: "memory-store-skill", icon: "🧠", originalPrice: 10 },
      { id: "14", name: "Web Search Skill", slug: "web-search-skill", icon: "🔎", originalPrice: 8 },
      { id: "12", name: "Email Composer Skill", slug: "email-composer-skill", icon: "📧", originalPrice: 9 },
      { id: "16", name: "Scheduler Skill", slug: "scheduler-skill", icon: "⏰", originalPrice: 8 },
    ],
  },
  {
    id: "b4",
    name: "Security & Testing Suite",
    description: "Complete security and quality assurance toolkit for production apps: vulnerability scanning, smart contract audits, load testing, and penetration testing.",
    price: 15,
    originalPrice: 42,
    atlasHint: "🛡️ Security-first development — let your agents handle comprehensive security testing automatically.",
    agents: [
      { id: "21", name: "Vulnerability Scanner", slug: "vulnerability-scanner", icon: "🛡️", originalPrice: 12 },
      { id: "22", name: "Smart Contract Auditor", slug: "smart-contract-auditor", icon: "🔐", originalPrice: 10 },
      { id: "26", name: "Load Testing Engine", slug: "load-testing-engine", icon: "⚡", originalPrice: 15 },
      { id: "24", name: "API Penetration Tester", slug: "api-pen-tester", icon: "🔧", originalPrice: 5 },
    ],
  },
  {
    id: "b5",
    name: "DeFi Trading Pro Pack",
    description: "Advanced DeFi trading capabilities: Ethereum oracle, MEV bot framework, Solana trading, and options strategies — everything for autonomous trading agents.",
    price: 18,
    originalPrice: 48,
    atlasHint: "📈 High-frequency trading ready — built for agents that trade 24/7 with minimal human oversight.",
    agents: [
      { id: "17", name: "Ethereum DeFi Oracle", slug: "ethereum-defi-oracle", icon: "⚡", originalPrice: 15 },
      { id: "18", name: "MEV Bot Framework", slug: "mev-bot-framework", icon: "🤖", originalPrice: 20 },
      { id: "19", name: "Solana Trading Engine", slug: "solana-trading-engine", icon: "☀️", originalPrice: 8 },
      { id: "20", name: "Options Strategy Builder", slug: "options-strategy-builder", icon: "📊", originalPrice: 5 },
    ],
  },
];

// 8 Niche Crypto Trading x402 Skills
const cryptoTradingSkills: Capability[] = [
  {
    id: "142",
    name: "Solana Rug Scanner",
    slug: "solana-rug-scanner", 
    description: "Analyzes Solana memecoin launches for rug risks. Input: token address or name. Returns: risk score, holder distribution analysis, dev wallet flags, liquidity lock status.",
    longDescription: "Advanced rug pull risk analysis for Solana memecoins. Analyzes holder distribution, dev wallet patterns, liquidity lock status, and social signals to generate comprehensive risk scores with actionable recommendations.",
    type: "api",
    category: "trading",
    pricePerCall: 0.03,
    x402Endpoint: "https://agent-bazaar.com/api/x402/solana-rug-scanner",
    icon: "🕵️",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["solana", "rug-scanner", "memecoin", "risk-analysis", "defi"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "143",
    name: "Funding Rate Arbitrage",
    slug: "funding-rate-arb",
    description: "Scans perpetual funding rates across exchanges (Hyperliquid, Orderly, dYdX). Identifies arbitrage opportunities >0.5%. Returns: pairs, rates, suggested entry/exit, estimated profit.",
    longDescription: "Professional funding rate arbitrage scanner across major perpetual exchanges. Identifies profitable rate differences, calculates optimal position sizes, and provides execution strategies for consistent yield generation.",
    type: "api", 
    category: "trading",
    pricePerCall: 0.05,
    x402Endpoint: "https://agent-bazaar.com/api/x402/funding-rate-arb",
    icon: "💰",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["funding-rates", "arbitrage", "perpetuals", "hyperliquid", "dydx"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "144",
    name: "AI Token Sentiment",
    slug: "ai-token-sentiment",
    description: "Sentiment analysis for AI/crypto tokens ($TAO, $FET, $RENDER, etc). Scrapes context from X/Reddit patterns. Returns: sentiment score, trending mentions, buy/sell signal.",
    longDescription: "Specialized sentiment analysis for AI-focused cryptocurrency tokens. Monitors social media patterns, news sentiment, and community engagement to generate actionable buy/sell signals for the AI crypto sector.",
    type: "api",
    category: "trading", 
    pricePerCall: 0.03,
    x402Endpoint: "https://agent-bazaar.com/api/x402/ai-token-sentiment",
    icon: "🤖",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["ai-tokens", "sentiment", "social-media", "tao", "fet"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "145",
    name: "Impermanent Loss Calculator",
    slug: "impermanent-loss-calc",
    description: "Calculates impermanent loss for DeFi LP positions. Input: token pair, entry prices, current prices, pool type. Returns: IL percentage, dollar impact, hedging recommendations.",
    longDescription: "Advanced impermanent loss calculator for DeFi liquidity providers. Analyzes IL across different pool types (Uniswap V2/V3, Curve), provides hedging strategies, and calculates optimal position management recommendations.",
    type: "api",
    category: "trading",
    pricePerCall: 0.02,
    x402Endpoint: "https://agent-bazaar.com/api/x402/impermanent-loss-calc",
    icon: "📉",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["impermanent-loss", "defi", "liquidity", "uniswap", "curve"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "146",
    name: "Whale Wallet Tracker",
    slug: "whale-wallet-tracker",
    description: "Monitors large wallet movements on Base/Solana/ETH. Input: wallet address or 'top whales'. Returns: recent large transactions, accumulation/distribution patterns, tokens held.",
    longDescription: "Comprehensive whale wallet tracking across Base, Solana, and Ethereum. Monitors large transactions, identifies accumulation patterns, and provides insights into institutional and high-net-worth trading behavior.",
    type: "api",
    category: "trading",
    pricePerCall: 0.03,
    x402Endpoint: "https://agent-bazaar.com/api/x402/whale-wallet-tracker",
    icon: "🐋",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["whale-tracking", "on-chain", "base", "solana", "ethereum"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "147",
    name: "MEV Opportunity Scanner",
    slug: "mev-opportunity-scanner",
    description: "Scans for MEV opportunities in DeFi pools. Returns: sandwich opportunities, arbitrage routes, liquidation targets, estimated profit.",
    longDescription: "Advanced MEV opportunity detection system. Scans mempool and DEX pools for arbitrage, sandwich, and liquidation opportunities with profit estimation and execution strategies for maximum extractable value.",
    type: "api",
    category: "trading",
    pricePerCall: 0.05,
    x402Endpoint: "https://agent-bazaar.com/api/x402/mev-opportunity-scanner",
    icon: "⚡",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["mev", "arbitrage", "sandwich", "liquidation", "defi"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "148", 
    name: "Cross-Market Signals",
    slug: "cross-market-signals",
    description: "Analyzes correlations between crypto and stocks (BTC vs NVDA, ETH vs QQQ). Generates cross-market trading signals. Returns: correlation data, divergence alerts, trade recommendations.",
    longDescription: "Sophisticated cross-asset correlation analysis between cryptocurrency and traditional markets. Identifies divergences, generates trading signals, and provides market regime insights for multi-asset strategies.",
    type: "api",
    category: "trading",
    pricePerCall: 0.04,
    x402Endpoint: "https://agent-bazaar.com/api/x402/cross-market-signals",
    icon: "📊",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["cross-market", "correlation", "stocks", "crypto", "signals"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "149",
    name: "Options Flow Analyzer", 
    slug: "options-flow-analyzer",
    description: "Analyzes crypto options flow (Deribit). Identifies unusual activity, large bets, put/call ratios. Returns: notable flows, implied volatility signals, institutional positioning.",
    longDescription: "Professional crypto options flow analysis for Deribit and major exchanges. Tracks institutional positioning, unusual activity, gamma levels, and volatility signals for sophisticated derivatives trading strategies.",
    type: "api",
    category: "trading",
    pricePerCall: 0.04,
    x402Endpoint: "https://agent-bazaar.com/api/x402/options-flow-analyzer",
    icon: "📈",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["options-flow", "deribit", "volatility", "gamma", "institutional"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906", 
    listingTier: "featured",
    mode: "natural",
  },
];

CAPABILITIES.push(...cryptoTradingSkills);

// Additional live-endpoint skills
CAPABILITIES.push(
  {
    id: "24",
    name: "Bankr Crypto Agent",
    slug: "bankr-agent",
    description: "Natural language crypto trading, transfers, portfolio management, and Polymarket betting via Bankr.",
    longDescription: "Full-featured crypto agent powered by Bankr. Trade tokens, check balances, send transfers, bet on Polymarket, deploy tokens, and manage your portfolio — all via natural language.",
    type: "api",
    category: "trading",
    pricePerCall: 0.05,
    x402Endpoint: "https://agent-bazaar.com/api/x402/bankr",
    icon: "💰",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["bankr", "trading", "crypto", "defi", "wallet"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: "natural",
  },
  {
    id: "25",
    name: "CI/CD Pipeline Generator",
    slug: "cicd-pipeline-gen",
    description: "Generate production-ready CI/CD pipelines for GitHub Actions, GitLab CI, and more.",
    longDescription: "AI-powered CI/CD pipeline generator. Describe your project and get complete pipeline configs.",
    type: "api",
    category: "cicd",
    pricePerCall: 0.03,
    x402Endpoint: "https://agent-bazaar.com/api/x402/cicd-generator",
    icon: "🔄",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["cicd", "devops", "github-actions", "pipeline"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "featured",
    mode: ["structured", "natural"],
  },
  {
    id: "26",
    name: "Sentiment Analyzer",
    slug: "sentiment-analysis",
    description: "Analyze sentiment of any text — returns score, emotion, and confidence.",
    longDescription: "AI-powered sentiment analysis. Returns sentiment score, emotion classification, confidence, and key phrases.",
    type: "api",
    category: "data-analysis",
    pricePerCall: 0.01,
    x402Endpoint: "https://agent-bazaar.com/api/x402/sentiment",
    icon: "😊",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["sentiment", "nlp", "analysis", "emotion"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "free",
    mode: ["structured", "natural"],
  },
  {
    id: "27",
    name: "SEO Keyword Extractor",
    slug: "keyword-extractor-skill",
    description: "Extract SEO keywords, search intent, and content suggestions from any text.",
    longDescription: "AI-powered keyword extraction and SEO analysis. Get ranked keywords, volume estimates, and intent classification.",
    type: "api",
    category: "content-writing",
    pricePerCall: 0.02,
    x402Endpoint: "https://agent-bazaar.com/api/x402/keyword-extractor",
    icon: "🔑",
    rating: 0,
    usageCount: 0,
    featured: true,
    tags: ["seo", "keywords", "content", "marketing"],
    creatorName: "Agent Bazaar",
    providerWallet: "0xDfaAF0f10c7822a1D620623Bd66e4a1C6B19B906",
    listingTier: "free",
    mode: ["structured", "natural"],
  },
);

export const REVIEWS: Review[] = [];