import { Capability, Review, Bundle } from "@/types";

export const CATEGORIES = [
  { value: "code-generation", label: "Code Generation", icon: "💻" },
  { value: "image-generation", label: "Image Generation", icon: "🎨" },
  { value: "data-analysis", label: "Data Analysis", icon: "📊" },
  { value: "content-writing", label: "Content Writing", icon: "✍️" },
  { value: "web-scraping", label: "Web Scraping", icon: "🕸️" },
  { value: "trading", label: "Trading", icon: "📈" },
  { value: "research", label: "Research", icon: "🔬" },
  { value: "automation", label: "Automation", icon: "⚙️" },
  { value: "security", label: "Security", icon: "🛡️" },
  { value: "testing", label: "Testing", icon: "🧪" },
  { value: "cicd", label: "CI/CD", icon: "🔄" },
  { value: "translation", label: "Translation", icon: "🌐" },
  { value: "voice-audio", label: "Voice & Audio", icon: "🎙️" },
  { value: "payments", label: "Payments", icon: "💳" },
  { value: "notifications", label: "Notifications", icon: "📱" },
  { value: "scheduling", label: "Scheduling", icon: "📅" },
] as const;

export const CAPABILITIES: Capability[] = [
  {
    id: "1",
    name: "GPT-4 Code Review",
    slug: "gpt4-code-review",
    description: "Automated code review via GPT-4. Submit a diff, get security analysis, bug detection, and style suggestions.",
    longDescription: "Production-grade code review powered by GPT-4. Catches security vulnerabilities, logic bugs, and style violations in any language.",
    type: "api",
    category: "code-generation",
    pricePerCall: 0.05,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/code-review",
    icon: "🔍",
    rating: 4.9,
    usageCount: 284000,
    featured: true,
    tags: ["code-review", "security", "gpt-4", "developer"],
    creatorName: "DevForge",
    listingTier: "spotlight",
  },
  {
    id: "2",
    name: "DALL-E Image Generator",
    slug: "dalle-image-gen",
    description: "Generate images from text prompts. x402-enabled — agents can generate images autonomously.",
    longDescription: "High-quality image generation via DALL-E 3. Supports all aspect ratios, styles, and quality levels.",
    type: "api",
    category: "image-generation",
    pricePerCall: 0.08,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/image-gen",
    icon: "🎨",
    rating: 4.7,
    usageCount: 512000,
    featured: true,
    tags: ["image", "dalle", "generation", "creative"],
    creatorName: "PixelMint",
    listingTier: "spotlight",
  },
  {
    id: "3",
    name: "Web Scraper API",
    slug: "web-scraper-api",
    description: "Extract structured data from any URL. Handles JS-rendered pages, anti-bot, and pagination.",
    longDescription: "Enterprise-grade web scraping. Returns clean JSON from any webpage with automatic anti-detection.",
    type: "api",
    category: "web-scraping",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/scraper",
    icon: "🕸️",
    rating: 4.6,
    usageCount: 1340000,
    featured: true,
    tags: ["scraping", "web", "data", "extraction"],
    creatorName: "CrawlLab",
  },
  {
    id: "4",
    name: "SEO Analyzer",
    slug: "seo-analyzer",
    description: "Full SEO audit for any URL. Technical SEO, content scoring, keyword gaps, and competitor analysis.",
    longDescription: "Comprehensive SEO analysis returning actionable recommendations. Covers on-page, technical, and content optimization.",
    type: "api",
    category: "content-writing",
    pricePerCall: 0.10,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/seo-audit",
    icon: "📈",
    rating: 4.8,
    usageCount: 89000,
    featured: true,
    tags: ["seo", "marketing", "analysis", "content"],
    creatorName: "RankForge",
    listingTier: "featured",
  },
  {
    id: "5",
    name: "SQL Query Generator",
    slug: "sql-query-gen",
    description: "Natural language to SQL. Supports PostgreSQL, MySQL, SQLite, and BigQuery dialects.",
    longDescription: "Describe what you need in English, get production-ready SQL. Handles complex joins, CTEs, and window functions.",
    type: "api",
    category: "code-generation",
    pricePerCall: 0.03,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/sql-gen",
    icon: "🗄️",
    rating: 4.5,
    usageCount: 167000,
    featured: false,
    tags: ["sql", "database", "query", "natural-language"],
    creatorName: "QueryCraft",
  },
  {
    id: "6",
    name: "git-audit CLI",
    slug: "git-audit-cli",
    description: "CLI tool that audits your git history for secrets, large files, and compliance issues.",
    longDescription: "Install via npm/brew. Scans entire git history for leaked credentials, oversized binaries, and policy violations.",
    type: "cli",
    category: "code-generation",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/git-audit",
    icon: "🔐",
    rating: 4.8,
    usageCount: 45000,
    featured: false,
    tags: ["git", "security", "cli", "audit"],
    creatorName: "SecureDev",
  },
  {
    id: "7",
    name: "CSV Intelligence",
    slug: "csv-intelligence",
    description: "Upload a CSV, ask questions in natural language. Returns charts, stats, and insights.",
    longDescription: "Data analysis without code. Upload any CSV and get instant statistical analysis, visualizations, and AI-powered insights.",
    type: "api",
    category: "data-analysis",
    pricePerCall: 0.06,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/csv-intel",
    icon: "📊",
    rating: 4.4,
    usageCount: 73000,
    featured: false,
    tags: ["csv", "analytics", "data", "visualization"],
    creatorName: "DataPilot",
  },
  {
    id: "8",
    name: "Blog Post Writer",
    slug: "blog-post-writer",
    description: "Generate SEO-optimized long-form blog posts. Includes outline, meta tags, and internal linking suggestions.",
    longDescription: "Feed it a keyword and tone, get a publish-ready blog post with SEO optimization baked in.",
    type: "api",
    category: "content-writing",
    pricePerCall: 0.15,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/blog-writer",
    icon: "✍️",
    rating: 4.7,
    usageCount: 198000,
    featured: true,
    tags: ["blog", "seo", "writing", "content"],
    creatorName: "ContentForge",
    listingTier: "featured",
  },
  {
    id: "9",
    name: "Crypto Price Oracle",
    slug: "crypto-price-oracle",
    description: "Real-time and historical crypto prices with technical indicators. Agent-native trading data.",
    longDescription: "Access real-time prices, OHLCV data, and 50+ technical indicators for any crypto pair. Built for trading agents.",
    type: "api",
    category: "trading",
    pricePerCall: 0.005,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/crypto-oracle",
    icon: "₿",
    rating: 4.6,
    usageCount: 2100000,
    featured: false,
    tags: ["crypto", "trading", "prices", "oracle"],
    creatorName: "ChainData",
  },
  {
    id: "10",
    name: "Research Summarizer",
    slug: "research-summarizer",
    description: "Summarize academic papers, reports, and documents. Returns structured key findings and citations.",
    longDescription: "Paste a URL or upload a PDF — get a structured summary with key findings, methodology, and citation-ready references.",
    type: "api",
    category: "research",
    pricePerCall: 0.04,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/research-summary",
    icon: "🔬",
    rating: 4.5,
    usageCount: 56000,
    featured: false,
    tags: ["research", "academic", "summary", "papers"],
    creatorName: "ScholarAI",
  },
  {
    id: "11",
    name: "deploy-cli",
    slug: "deploy-cli",
    description: "One-command deploy to any cloud. Supports Vercel, AWS, GCP, and Fly.io with zero config.",
    longDescription: "CLI tool that detects your framework and deploys to your preferred cloud provider with sensible defaults.",
    type: "cli",
    category: "automation",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/deploy-cli",
    icon: "🚀",
    rating: 4.3,
    usageCount: 34000,
    featured: false,
    tags: ["deploy", "cli", "cloud", "devops"],
    creatorName: "ShipFast",
  },
  {
    id: "12",
    name: "Email Composer Skill",
    slug: "email-composer-skill",
    description: "Agent skill for composing context-aware emails. Drop into any agent framework as a tool.",
    longDescription: "A composable skill that any AI agent can use. Given context and intent, drafts professional emails with proper tone.",
    type: "skill",
    category: "automation",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/email-compose",
    icon: "📧",
    rating: 4.6,
    usageCount: 127000,
    featured: false,
    tags: ["email", "skill", "agent", "automation"],
    creatorName: "ToolSmith",
  },
  {
    id: "13",
    name: "Memory Store Skill",
    slug: "memory-store-skill",
    description: "Persistent vector memory for any agent. Store, retrieve, and search context across sessions.",
    longDescription: "Give any agent long-term memory. ChromaDB-backed vector store with semantic search — drop in as a skill via x402.",
    type: "skill",
    category: "automation",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/memory-store",
    icon: "🧠",
    rating: 4.9,
    usageCount: 340000,
    featured: true,
    tags: ["memory", "vector", "rag", "agent", "skill"],
    creatorName: "MemoryAI",
    listingTier: "spotlight",
  },
  {
    id: "14",
    name: "Web Search Skill",
    slug: "web-search-skill",
    description: "Real-time web search for agents. Returns structured results with snippets and sources.",
    longDescription: "Drop-in web search capability for any agent framework. Returns ranked results with full page content extraction.",
    type: "skill",
    category: "research",
    pricePerCall: 0.005,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/web-search",
    icon: "🔎",
    rating: 4.8,
    usageCount: 890000,
    featured: true,
    tags: ["search", "web", "skill", "agent", "research"],
    creatorName: "SearchCraft",
    listingTier: "featured",
  },
  {
    id: "15",
    name: "bankr-cli",
    slug: "bankr-cli",
    description: "CLI for on-chain agent actions. Send tokens, check balances, swap — all from a shell or agent.",
    longDescription: "The self-funding agent CLI. Built for agents that need to interact with Base and EVM chains autonomously. x402-compatible.",
    type: "cli",
    category: "trading",
    pricePerCall: 0.001,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/bankr-cli",
    icon: "🏦",
    rating: 4.9,
    usageCount: 210000,
    featured: true,
    tags: ["crypto", "cli", "onchain", "agent", "base"],
    creatorName: "Bankr",
    listingTier: "spotlight",
  },
  {
    id: "16",
    name: "Scheduler Skill",
    slug: "scheduler-skill",
    description: "Give any agent the ability to schedule future tasks, reminders, and recurring jobs.",
    longDescription: "Cron-based task scheduling as a composable skill. Agents can schedule their own follow-ups and recurring workflows.",
    type: "skill",
    category: "automation",
    pricePerCall: 0.005,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/scheduler",
    icon: "⏰",
    rating: 4.5,
    usageCount: 67000,
    featured: false,
    tags: ["scheduling", "cron", "skill", "agent", "automation"],
    creatorName: "TimeCraft",
  },
  // TRADING EXPANSION
  {
    id: "17",
    name: "DeFi Yield Scanner",
    slug: "defi-yield-scanner",
    description: "Real-time DeFi yield opportunities across major protocols. Returns APYs, risks, and optimal strategies.",
    longDescription: "Scans Uniswap, Aave, Compound, and 20+ protocols for yield opportunities. Includes impermanent loss calculations and risk scores.",
    type: "api",
    category: "trading",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/defi-yield",
    icon: "🌾",
    rating: 4.7,
    usageCount: 145000,
    featured: false,
    tags: ["defi", "yield", "farming", "protocol", "apy"],
    creatorName: "YieldHunter",
  },
  {
    id: "18",
    name: "MEV Protection API",
    slug: "mev-protection-api",
    description: "Anti-MEV transaction submission. Route trades through private mempools to prevent frontrunning.",
    longDescription: "Protect your trading agents from MEV attacks. Submit transactions through Flashbots and other private mempools with optimal timing.",
    type: "api",
    category: "trading",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/mev-protect",
    icon: "🛡️",
    rating: 4.8,
    usageCount: 89000,
    featured: true,
    tags: ["mev", "protection", "flashbots", "trading", "security"],
    creatorName: "ShieldTrade",
    listingTier: "featured",
  },
  {
    id: "19",
    name: "Solana Trading Engine",
    slug: "solana-trading-engine",
    description: "High-speed Solana DEX trading with Jupiter aggregation. Sub-second execution for trading bots.",
    longDescription: "Built for Solana trading agents. Executes swaps across all major DEXs with optimal routing via Jupiter. Handles slippage and priority fees.",
    type: "api",
    category: "trading",
    pricePerCall: 0.008,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/solana-trade",
    icon: "⚡",
    rating: 4.6,
    usageCount: 234000,
    featured: true,
    tags: ["solana", "dex", "jupiter", "trading", "speed"],
    creatorName: "SolTrade",
    listingTier: "featured",
  },
  {
    id: "20",
    name: "Options Pricing Oracle",
    slug: "options-pricing-oracle",
    description: "Real-time options pricing with Greeks. Black-Scholes and exotic models for traditional and crypto options.",
    longDescription: "Professional options pricing for trading algorithms. Calculates fair value, implied volatility, and all Greeks in real-time.",
    type: "api",
    category: "trading",
    pricePerCall: 0.015,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/options-price",
    icon: "📊",
    rating: 4.9,
    usageCount: 67000,
    featured: false,
    tags: ["options", "greeks", "pricing", "volatility", "derivatives"],
    creatorName: "DerivTech",
  },
  // SECURITY SCANNING
  {
    id: "21",
    name: "Smart Contract Auditor",
    slug: "smart-contract-auditor",
    description: "Automated security analysis for Solidity contracts. Detects vulnerabilities, gas issues, and best practice violations.",
    longDescription: "Enterprise-grade smart contract security analysis. Powered by Mythril, Slither, and custom heuristics. Returns detailed vulnerability reports.",
    type: "api",
    category: "security",
    pricePerCall: 0.12,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/contract-audit",
    icon: "🔒",
    rating: 4.8,
    usageCount: 23000,
    featured: true,
    tags: ["smart-contract", "solidity", "security", "audit", "vulnerability"],
    creatorName: "ChainGuard",
    listingTier: "featured",
  },
  {
    id: "22",
    name: "Domain Security Scanner",
    slug: "domain-security-scanner",
    description: "Comprehensive domain security audit. SSL, DNS, headers, subdomains, and vulnerability scanning.",
    longDescription: "Full security assessment of any domain. Checks SSL configuration, security headers, DNS records, exposed subdomains, and common vulnerabilities.",
    type: "api",
    category: "security",
    pricePerCall: 0.08,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/domain-scan",
    icon: "🌐",
    rating: 4.7,
    usageCount: 156000,
    featured: false,
    tags: ["domain", "ssl", "dns", "security", "vulnerability"],
    creatorName: "SecureDomain",
  },
  {
    id: "23",
    name: "API Security Tester",
    slug: "api-security-tester",
    description: "Automated API penetration testing. OWASP Top 10, injection attacks, and authentication bypass detection.",
    longDescription: "Security testing for REST and GraphQL APIs. Tests for injection, broken auth, rate limiting, and data exposure vulnerabilities.",
    type: "api",
    category: "security",
    pricePerCall: 0.15,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/api-pentest",
    icon: "⚔️",
    rating: 4.9,
    usageCount: 45000,
    featured: true,
    tags: ["api", "pentest", "owasp", "security", "vulnerability"],
    creatorName: "PentestPro",
    listingTier: "spotlight",
  },
  {
    id: "24",
    name: "Dependency Vulnerability Check",
    slug: "dependency-vuln-check",
    description: "Scan package dependencies for known vulnerabilities. Supports npm, pip, composer, and 10+ package managers.",
    longDescription: "Continuous dependency monitoring across all major package ecosystems. Returns CVE details, severity scores, and upgrade paths.",
    type: "api",
    category: "security",
    pricePerCall: 0.05,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/dep-scan",
    icon: "📦",
    rating: 4.6,
    usageCount: 278000,
    featured: false,
    tags: ["dependencies", "vulnerability", "cve", "npm", "security"],
    creatorName: "VulnScan",
  },
  // TESTING
  {
    id: "25",
    name: "E2E Test Generator",
    slug: "e2e-test-generator",
    description: "Generate Playwright/Cypress tests from user flows. Record actions, get production-ready test code.",
    longDescription: "Turn user workflows into automated tests. Records browser interactions and generates maintainable Playwright or Cypress test suites.",
    type: "api",
    category: "testing",
    pricePerCall: 0.10,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/e2e-gen",
    icon: "🎭",
    rating: 4.5,
    usageCount: 87000,
    featured: false,
    tags: ["e2e", "playwright", "cypress", "testing", "automation"],
    creatorName: "TestForge",
  },
  {
    id: "26",
    name: "Load Testing API",
    slug: "load-testing-api",
    description: "Distributed load testing from 50+ global locations. Stress test APIs and web apps at scale.",
    longDescription: "Cloud-based load testing with realistic traffic patterns. Generate millions of requests with detailed performance metrics and bottleneck analysis.",
    type: "api",
    category: "testing",
    pricePerCall: 0.25,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/load-test",
    icon: "⚡",
    rating: 4.7,
    usageCount: 34000,
    featured: true,
    tags: ["load-testing", "performance", "stress", "scale", "api"],
    creatorName: "LoadRunner",
    listingTier: "featured",
  },
  {
    id: "27",
    name: "Visual Regression Detector",
    slug: "visual-regression-detector",
    description: "AI-powered visual testing. Detects UI changes, layout shifts, and visual bugs across browsers.",
    longDescription: "Screenshot-based visual testing with ML-powered diff detection. Automatically identifies meaningful visual changes while ignoring noise.",
    type: "api",
    category: "testing",
    pricePerCall: 0.06,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/visual-test",
    icon: "👁️",
    rating: 4.8,
    usageCount: 123000,
    featured: false,
    tags: ["visual", "regression", "ui", "testing", "screenshots"],
    creatorName: "VisualQA",
  },
  {
    id: "28",
    name: "API Fuzz Tester",
    slug: "api-fuzz-tester",
    description: "Intelligent API fuzzing to discover edge cases, crashes, and unexpected behaviors.",
    longDescription: "Advanced fuzzing engine that generates millions of test inputs to find API edge cases, crashes, and security vulnerabilities.",
    type: "api",
    category: "testing",
    pricePerCall: 0.08,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/api-fuzz",
    icon: "🎯",
    rating: 4.6,
    usageCount: 56000,
    featured: false,
    tags: ["fuzzing", "api", "testing", "edge-cases", "security"],
    creatorName: "FuzzMaster",
  },
  // CI/CD
  {
    id: "29",
    name: "GitHub Actions Optimizer",
    slug: "github-actions-optimizer",
    description: "Analyze and optimize GitHub Actions workflows. Reduce build times and compute costs automatically.",
    longDescription: "AI-powered CI/CD optimization. Analyzes workflow performance, suggests caching strategies, and optimizes job parallelization.",
    type: "api",
    category: "cicd",
    pricePerCall: 0.07,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/actions-optimize",
    icon: "⚙️",
    rating: 4.7,
    usageCount: 78000,
    featured: false,
    tags: ["github-actions", "ci", "optimization", "performance", "devops"],
    creatorName: "OptimizeCI",
  },
  {
    id: "30",
    name: "Docker Build Accelerator",
    slug: "docker-build-accelerator",
    description: "Optimize Docker builds with intelligent layer caching and multi-stage optimization.",
    longDescription: "Speeds up Docker builds by 5-10x through smart layer ordering, dependency analysis, and build cache optimization.",
    type: "api",
    category: "cicd",
    pricePerCall: 0.05,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/docker-optimize",
    icon: "🐳",
    rating: 4.8,
    usageCount: 145000,
    featured: true,
    tags: ["docker", "build", "optimization", "caching", "devops"],
    creatorName: "DockerSpeed",
    listingTier: "featured",
  },
  {
    id: "31",
    name: "Pipeline Health Monitor",
    slug: "pipeline-health-monitor",
    description: "Real-time CI/CD pipeline monitoring with anomaly detection and failure prediction.",
    longDescription: "Monitors pipeline metrics across all major CI platforms. Uses ML to predict failures and suggest optimizations before issues occur.",
    type: "api",
    category: "cicd",
    pricePerCall: 0.03,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/pipeline-health",
    icon: "📊",
    rating: 4.6,
    usageCount: 92000,
    featured: false,
    tags: ["monitoring", "pipeline", "ci", "health", "prediction"],
    creatorName: "PipeWatch",
  },
  {
    id: "32",
    name: "Deployment Rollback API",
    slug: "deployment-rollback-api",
    description: "Instant rollbacks across cloud providers. Zero-downtime deployment reversal with health checks.",
    longDescription: "Universal deployment rollback service supporting AWS, GCP, Azure, and Vercel. Automated health monitoring with instant rollback triggers.",
    type: "api",
    category: "cicd",
    pricePerCall: 0.04,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/rollback",
    icon: "↩️",
    rating: 4.9,
    usageCount: 67000,
    featured: true,
    tags: ["rollback", "deployment", "cloud", "reliability", "devops"],
    creatorName: "SafeDeploy",
    listingTier: "featured",
  },
  // TRANSLATION
  {
    id: "33",
    name: "Context-Aware Translator",
    slug: "context-aware-translator",
    description: "Professional translation with domain context. Technical, legal, medical, and creative content specialization.",
    longDescription: "Goes beyond Google Translate. Understands domain context, maintains tone, and handles technical terminology across 50+ languages.",
    type: "api",
    category: "translation",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/translate-pro",
    icon: "🌍",
    rating: 4.8,
    usageCount: 234000,
    featured: true,
    tags: ["translation", "context", "professional", "multilingual", "domain"],
    creatorName: "LinguaAI",
    listingTier: "featured",
  },
  {
    id: "34",
    name: "Code Comment Translator",
    slug: "code-comment-translator",
    description: "Translate code comments and documentation while preserving technical accuracy and formatting.",
    longDescription: "Specialized for developer content. Translates code comments, README files, and API docs while maintaining technical precision.",
    type: "api",
    category: "translation",
    pricePerCall: 0.015,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/code-translate",
    icon: "💻",
    rating: 4.7,
    usageCount: 89000,
    featured: false,
    tags: ["translation", "code", "documentation", "developer", "technical"],
    creatorName: "DevTranslate",
  },
  {
    id: "35",
    name: "Real-time Speech Translator",
    slug: "realtime-speech-translator",
    description: "Live audio translation in 40+ languages. Perfect for agent-to-agent multilingual communication.",
    longDescription: "Real-time speech-to-speech translation with voice cloning. Maintains speaker characteristics across language barriers.",
    type: "api",
    category: "translation",
    pricePerCall: 0.08,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/speech-translate",
    icon: "🎤",
    rating: 4.6,
    usageCount: 156000,
    featured: false,
    tags: ["speech", "translation", "realtime", "voice", "multilingual"],
    creatorName: "VoiceTranslate",
  },
  // VOICE & AUDIO
  {
    id: "36",
    name: "Voice Cloning Studio",
    slug: "voice-cloning-studio",
    description: "Create custom AI voices from 30 seconds of audio. Perfect for agent personalities and brand voices.",
    longDescription: "High-quality voice cloning with minimal training data. Generate natural speech in any voice with emotional control and accent support.",
    type: "api",
    category: "voice-audio",
    pricePerCall: 0.12,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/voice-clone",
    icon: "🎭",
    rating: 4.9,
    usageCount: 78000,
    featured: true,
    tags: ["voice", "cloning", "tts", "ai", "personality"],
    creatorName: "VoiceLab",
    listingTier: "spotlight",
  },
  {
    id: "37",
    name: "Audio Enhancement API",
    slug: "audio-enhancement-api",
    description: "AI-powered audio cleanup. Remove noise, enhance clarity, and improve podcast/meeting recordings.",
    longDescription: "Professional audio post-processing powered by AI. Removes background noise, enhances speech clarity, and normalizes volume levels.",
    type: "api",
    category: "voice-audio",
    pricePerCall: 0.04,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/audio-enhance",
    icon: "🎧",
    rating: 4.7,
    usageCount: 145000,
    featured: false,
    tags: ["audio", "enhancement", "noise-reduction", "podcast", "quality"],
    creatorName: "AudioFix",
  },
  {
    id: "38",
    name: "Music Generation Engine",
    slug: "music-generation-engine",
    description: "Generate background music and jingles from text prompts. Royalty-free AI composition.",
    longDescription: "Create custom music for videos, podcasts, and apps. Supports multiple genres, moods, and instruments with stem separation.",
    type: "api",
    category: "voice-audio",
    pricePerCall: 0.15,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/music-gen",
    icon: "🎵",
    rating: 4.5,
    usageCount: 67000,
    featured: false,
    tags: ["music", "generation", "ai", "composition", "royalty-free"],
    creatorName: "MelodyAI",
  },
  {
    id: "39",
    name: "Speech-to-Text Pro",
    slug: "speech-to-text-pro",
    description: "Ultra-accurate transcription with speaker diarization and custom vocabulary support.",
    longDescription: "Enterprise speech recognition with 99%+ accuracy. Handles accents, multiple speakers, and technical jargon with custom language models.",
    type: "api",
    category: "voice-audio",
    pricePerCall: 0.03,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/stt-pro",
    icon: "📝",
    rating: 4.8,
    usageCount: 456000,
    featured: true,
    tags: ["transcription", "stt", "accuracy", "diarization", "enterprise"],
    creatorName: "TranscribeAI",
    listingTier: "featured",
  },
  // PAYMENTS
  {
    id: "40",
    name: "Stripe Connect API",
    slug: "stripe-connect-api",
    description: "Complete Stripe integration for marketplaces. Handle payments, splits, and compliance automatically.",
    longDescription: "Full Stripe Connect implementation with marketplace support, automated KYC, tax handling, and multi-party payment splits.",
    type: "api",
    category: "payments",
    pricePerCall: 0.05,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/stripe-connect",
    icon: "💳",
    rating: 4.8,
    usageCount: 89000,
    featured: true,
    tags: ["stripe", "payments", "marketplace", "connect", "compliance"],
    creatorName: "PayFlow",
    listingTier: "featured",
  },
  {
    id: "41",
    name: "Crypto Payment Processor",
    slug: "crypto-payment-processor",
    description: "Accept payments in 50+ cryptocurrencies with instant fiat conversion and compliance tools.",
    longDescription: "Complete crypto payment solution with automatic conversion to stablecoins or fiat, tax reporting, and regulatory compliance.",
    type: "api",
    category: "payments",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/crypto-pay",
    icon: "₿",
    rating: 4.7,
    usageCount: 123000,
    featured: false,
    tags: ["crypto", "payments", "bitcoin", "ethereum", "conversion"],
    creatorName: "CryptoPay",
  },
  {
    id: "42",
    name: "Invoice Generator API",
    slug: "invoice-generator-api",
    description: "Generate professional invoices with automatic payment reminders and multi-currency support.",
    longDescription: "Complete invoicing solution with PDF generation, payment tracking, automated reminders, and integration with major accounting systems.",
    type: "api",
    category: "payments",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/invoice-gen",
    icon: "📄",
    rating: 4.6,
    usageCount: 234000,
    featured: false,
    tags: ["invoice", "billing", "accounting", "pdf", "reminders"],
    creatorName: "BillBot",
  },
  {
    id: "43",
    name: "Subscription Manager",
    slug: "subscription-manager",
    description: "Complete subscription billing with dunning management, usage tracking, and revenue analytics.",
    longDescription: "Full-featured subscription platform handling recurring billing, proration, dunning, churn prevention, and detailed revenue analytics.",
    type: "api",
    category: "payments",
    pricePerCall: 0.08,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/subscription",
    icon: "🔄",
    rating: 4.9,
    usageCount: 67000,
    featured: true,
    tags: ["subscription", "recurring", "billing", "saas", "analytics"],
    creatorName: "SubFlow",
    listingTier: "featured",
  },
  // NOTIFICATIONS
  {
    id: "44",
    name: "Multi-Channel Notifier",
    slug: "multi-channel-notifier",
    description: "Send notifications across email, SMS, Slack, Discord, and 20+ platforms from one API.",
    longDescription: "Universal notification service supporting email, SMS, push notifications, Slack, Discord, Teams, and custom webhooks with delivery guarantees.",
    type: "api",
    category: "notifications",
    pricePerCall: 0.005,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/notify",
    icon: "📢",
    rating: 4.8,
    usageCount: 567000,
    featured: true,
    tags: ["notifications", "email", "sms", "slack", "multi-channel"],
    creatorName: "NotifyHub",
    listingTier: "featured",
  },
  {
    id: "45",
    name: "Smart Alert Manager",
    slug: "smart-alert-manager",
    description: "Intelligent alert routing with escalation policies and noise reduction. Prevent alert fatigue.",
    longDescription: "ML-powered alert management that learns from your team's responses. Reduces noise, groups related alerts, and handles escalation automatically.",
    type: "api",
    category: "notifications",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/smart-alerts",
    icon: "🚨",
    rating: 4.7,
    usageCount: 89000,
    featured: false,
    tags: ["alerts", "escalation", "smart", "ml", "fatigue"],
    creatorName: "AlertMind",
  },
  {
    id: "46",
    name: "Push Notification Service",
    slug: "push-notification-service",
    description: "Mobile and web push notifications with advanced targeting and A/B testing capabilities.",
    longDescription: "Complete push notification platform supporting iOS, Android, and web push with segmentation, personalization, and campaign analytics.",
    type: "api",
    category: "notifications",
    pricePerCall: 0.002,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/push-notify",
    icon: "📱",
    rating: 4.6,
    usageCount: 1200000,
    featured: false,
    tags: ["push", "mobile", "web", "targeting", "analytics"],
    creatorName: "PushPro",
  },
  // SCHEDULING
  {
    id: "47",
    name: "Calendar Sync API",
    slug: "calendar-sync-api",
    description: "Two-way sync with Google Calendar, Outlook, and Apple Calendar. Schedule meetings across platforms.",
    longDescription: "Universal calendar integration with conflict detection, availability checking, and automated meeting scheduling across all major calendar providers.",
    type: "api",
    category: "scheduling",
    pricePerCall: 0.02,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/calendar-sync",
    icon: "📅",
    rating: 4.8,
    usageCount: 345000,
    featured: true,
    tags: ["calendar", "sync", "google", "outlook", "meetings"],
    creatorName: "CalendarPro",
    listingTier: "featured",
  },
  {
    id: "48",
    name: "Smart Scheduler AI",
    slug: "smart-scheduler-ai",
    description: "AI-powered meeting scheduling that finds optimal times for all participants across time zones.",
    longDescription: "Intelligent scheduling assistant that considers preferences, time zones, working hours, and meeting patterns to find the best meeting times.",
    type: "api",
    category: "scheduling",
    pricePerCall: 0.03,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/smart-schedule",
    icon: "🤖",
    rating: 4.9,
    usageCount: 78000,
    featured: true,
    tags: ["ai", "scheduling", "timezone", "optimization", "meetings"],
    creatorName: "ScheduleAI",
    listingTier: "spotlight",
  },
  {
    id: "49",
    name: "Event Booking Platform",
    slug: "event-booking-platform",
    description: "Complete event booking system with payments, tickets, and automated confirmations.",
    longDescription: "Full-featured event management platform handling registrations, payments, ticket generation, and automated email sequences.",
    type: "api",
    category: "scheduling",
    pricePerCall: 0.05,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/event-booking",
    icon: "🎟️",
    rating: 4.7,
    usageCount: 156000,
    featured: false,
    tags: ["events", "booking", "tickets", "payments", "automation"],
    creatorName: "EventFlow",
  },
  {
    id: "50",
    name: "Appointment Reminder Bot",
    slug: "appointment-reminder-bot",
    description: "Automated appointment reminders via SMS, email, and voice calls with rescheduling links.",
    longDescription: "Reduces no-shows by 80% with smart reminder sequences. Handles confirmations, rescheduling, and cancellations automatically.",
    type: "api",
    category: "scheduling",
    pricePerCall: 0.01,
    x402Endpoint: "https://api.agentbazaar.xyz/x402/appointment-reminder",
    icon: "⏰",
    rating: 4.6,
    usageCount: 234000,
    featured: false,
    tags: ["reminders", "appointments", "sms", "voice", "automation"],
    creatorName: "RemindBot",
  },
];

// Alias for backwards compatibility
export const AGENTS = CAPABILITIES;

export const BUNDLES: Bundle[] = [
  {
    id: "b1",
    name: "Developer Skills Pack",
    description: "Everything a coding agent needs: code review, SQL generation, git auditing, and one-command deploys. Ship faster with AI assistance on every step.",
    price: 7,
    originalPrice: 19,
    atlasHint: "⚡ Atlas-ready — these skills run automatically in your dev workflows.",
    agents: [
      { id: "1", name: "GPT-4 Code Review", slug: "gpt4-code-review", icon: "🔍", originalPrice: 5 },
      { id: "5", name: "SQL Query Generator", slug: "sql-query-gen", icon: "🗄️", originalPrice: 3 },
      { id: "6", name: "git-audit CLI", slug: "git-audit-cli", icon: "🔐", originalPrice: 4 },
      { id: "11", name: "deploy-cli", slug: "deploy-cli", icon: "🚀", originalPrice: 7 },
    ],
  },
  {
    id: "b2",
    name: "Content & Research Pack",
    description: "Your content agent's full toolkit: write blog posts, audit SEO, scrape sources, and summarize research — all on autopilot via x402.",
    price: 9,
    originalPrice: 29,
    atlasHint: "✍️ Pair with Atlas to run a fully automated content pipeline.",
    agents: [
      { id: "8", name: "Blog Post Writer", slug: "blog-post-writer", icon: "✍️", originalPrice: 8 },
      { id: "4", name: "SEO Analyzer", slug: "seo-analyzer", icon: "📈", originalPrice: 10 },
      { id: "3", name: "Web Scraper API", slug: "web-scraper-api", icon: "🕸️", originalPrice: 5 },
      { id: "10", name: "Research Summarizer", slug: "research-summarizer", icon: "🔬", originalPrice: 6 },
    ],
  },
  {
    id: "b3",
    name: "Agent Infrastructure Pack",
    description: "Core infrastructure for any autonomous agent: persistent memory, real-time web search, email composition, and task scheduling — all x402-native.",
    price: 12,
    originalPrice: 35,
    atlasHint: "🧠 The foundation layer for production-grade Atlas agents.",
    agents: [
      { id: "13", name: "Memory Store Skill", slug: "memory-store-skill", icon: "🧠", originalPrice: 10 },
      { id: "14", name: "Web Search Skill", slug: "web-search-skill", icon: "🔎", originalPrice: 8 },
      { id: "12", name: "Email Composer Skill", slug: "email-composer-skill", icon: "📧", originalPrice: 9 },
      { id: "16", name: "Scheduler Skill", slug: "scheduler-skill", icon: "⏰", originalPrice: 8 },
    ],
  },
  {
    id: "b4",
    name: "Trading & DeFi Master Pack",
    description: "Complete trading agent toolkit: DeFi yields, MEV protection, Solana DEX access, options pricing, and secure contract auditing. Dominate crypto markets safely.",
    price: 15,
    originalPrice: 42,
    atlasHint: "🚀 Power up your Atlas trading agents with institutional-grade tools.",
    agents: [
      { id: "17", name: "DeFi Yield Scanner", slug: "defi-yield-scanner", icon: "🌾", originalPrice: 8 },
      { id: "18", name: "MEV Protection API", slug: "mev-protection-api", icon: "🛡️", originalPrice: 12 },
      { id: "19", name: "Solana Trading Engine", slug: "solana-trading-engine", icon: "⚡", originalPrice: 10 },
      { id: "20", name: "Options Pricing Oracle", slug: "options-pricing-oracle", icon: "📊", originalPrice: 12 },
    ],
  },
  {
    id: "b5",
    name: "Security & Testing Suite",
    description: "Enterprise security arsenal: smart contract audits, API pentesting, visual regression detection, and load testing. Ship with confidence.",
    price: 18,
    originalPrice: 55,
    atlasHint: "🔒 Essential security layer for production Atlas deployments.",
    agents: [
      { id: "21", name: "Smart Contract Auditor", slug: "smart-contract-auditor", icon: "🔒", originalPrice: 15 },
      { id: "23", name: "API Security Tester", slug: "api-security-tester", icon: "⚔️", originalPrice: 18 },
      { id: "26", name: "Load Testing API", slug: "load-testing-api", icon: "⚡", originalPrice: 12 },
      { id: "27", name: "Visual Regression Detector", slug: "visual-regression-detector", icon: "👁️", originalPrice: 10 },
    ],
  },
];

export const REVIEWS: Review[] = [
  { id: "r1", capabilityId: "1", userName: "DevAlex", rating: 5, comment: "Catches bugs my team misses. The x402 integration means my CI agent just pays per review automatically.", date: "2026-02-01" },
  { id: "r2", capabilityId: "3", userName: "DataHunter", rating: 5, comment: "Finally a scraper that handles SPAs. My research agent uses this autonomously now.", date: "2026-01-28" },
  { id: "r3", capabilityId: "8", userName: "ContentKing", rating: 5, comment: "30 blog posts last month, all page 1. My content agent calls this on autopilot.", date: "2026-02-05" },
  { id: "r4", capabilityId: "9", userName: "CryptoBot", rating: 4, comment: "Rock-solid oracle. My trading agent makes 50+ calls/day at $0.005 each. Incredible value.", date: "2026-02-10" },
];